### PR TITLE
file decryption and open

### LINKED ISSUE #20: Add support for viewing downloaded documents
As a journalist I want to be able to view a file submitted by a source in a common format (e.g., PDF, JPG, DOC, AVI) so that I can inspect it for potential newsworthiness.

As shown in the [messaging prototype](https://eloquence.github.io/workstation-messaging/), after a document has been downloaded, it should be possible to launch an appropriate viewer application to  open a decrypted submission, ideally in a hardened disposable VM.

### LINKED ISSUE #66: Add support for decrypting downloaded documents
To build on #64, we should add support for decrypting documents once a file (i.e. non-message submission) has been downloaded.

### PR DESCRIPTION
**Pull request by redshiftzero**
Closes #20, closes #66

Supersedes #102 (brought @ntoll's work there where he added the file opening in this PR with some tiny changes from testing in my SD Qubes workstation)

This is to get us to a state where we can build the first round of securedrop-client package and integrate it into the workstation repo

# Testing

## On Qubes

1. Single click a downloaded file should download, decrypt, and save
2. Single click again once the button changes to "Open" should open the file using whatever default application for that mime type in a Disposable VM

## On non-Qubes

1. Make sure you added the test private key [mentioned here](https://github.com/freedomofpress/securedrop-client#run-the-client) to your GPG keyring
2. To test the file opening part of this, you'll need to apply a diff like the following for mac (just swap out `open` for `xdg-open` on Linux):

```diff
diff --git a/securedrop_client/logic.py b/securedrop_client/logic.py
index 8b5c27c..99bbe4f 100644
@@ -462,6 +462,11 @@ class Client(QObject):
             process = QProcess(self)
             process.start(command, args)
         else:  # pragma: no cover
+            # Running on mac.
+            command = "open"
+            args = [submission_filepath]
+            process = QProcess(self)
+            process.start(command, args)
             # Non Qubes OS. Just log the event for now.
             logger.info('Opening file "{}".'.format(submission_filepath))
```

Then the behavior described for Qubes above should work as expected (except obviously no DispVM):

file-decrypt-open

### CODE REVIEW

**Comment by redshiftzero** [comment]
hey @zenmonkeykstep if you have chance today please give this a spin in Qubes

**Comment by joshuathayer** [comment]
Also, ran this on my Qubes machine against @emkll 's SD server, and successfully downloaded and opened (in a disp VM) files.

**Comment by redshiftzero** [comment]
Filed the following issues for followup here (and marked them with the `help wanted` tag if I think they would be good for hackathon participants): #117 #116 #115

**Comment by redshiftzero** [comment]
thanks for testing and reviewing @joshuathayer!

**Pull request merged**
