### PR TITLE
Activity indicator for file download / decryption.

### LINKED ISSUE #288: Implement download/decryption activity indicator (first iteration)
Related to #261, but note that we currently do not have _any_ activity indicator in the client, so this is not merely a styling question.

Per @redshiftzero the current stages a successful download goes through are as follows:

1. Not downloaded
2. Download started - download user feedback begins
3. Download finishes - download user feedback ends
3. Decryption is attempted - decryption user feedback begins
4. Decryption is finished - decryption user feedback ends
5. "Open" is shown

Currently, the client skips directly from "Download" to "Open" without any activity indication in between.

@ninavizz has committed to delivering iterated designs prior to the 4/3-4/17 sprint kick-off, ideally these designs should cover:
- download activity indicator and place for contextual messages
- decryption activity indicator and place for contextual messages
- final "Open" state

For the purpose of a first iteration, the following are **out of scope**:
- displaying progress (0%, 25%, etc.)
- displaying filenames of decrypted files

### PR DESCRIPTION
**Pull request by ntoll**
# Description

Fixes #288.

Q: downloading involves network latency. Decrypting is pretty instantaneous for me (am I missing something here?).

Here's a screenie-gif of the progress so far:

download_spinner

The behaviour in the screenie (as of time of writing) is only what is implemented in the PR (along with a test update).

Please confirm:

* The spinner is what you want. I couldn't work out @ninavizz's linked to GitHub comment about where to find the spinner. In the end I've used the `refresh_active.svg` image. Updates to this welcome. :-)
* The Zeplin stuff about this (see the bottom of the screen for https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d1301b692a0cd04b141175d) appears so that both the download and downloading states are superimposed over each other. Not quite sure what to make of that, but I've tried to make it look as close as I can discern.
* This is enough of a solution to address #288 for the time being.

# Test Plan

Added additions to relevant unit test.

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [X] These changes should not need testing in Qubes

If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to be updated. Please check as applicable:

 - [ ] I have submitted a separate PR to the [packaging repo](https://github.com/freedomofpress/securedrop-debian-packaging)
 - [ ] No update to the packaging logic (e.g., AppArmor profile) is required for these changes
 - [ ] I don't know and would appreciate guidance

### CODE REVIEW

**Comment by eloquence** [comment]
> Decrypting is pretty instantaneous for me (am I missing something here?).

Upload size limit for individual files is 500 MB. How long does it take at or near that limit in Qubes?

**Comment by ntoll** [comment]
@eloquence aha... good point. I've just been uploading goofy images and the like. In any case, the worst that will happen is the indicator will be simply displayed for longer.

**Comment by ninavizz** [comment]
- I would like to add a minimum-time of 3-seconds to the "Active" state
- The states all appear to note line-up quite right... namely, from "Active" to "Downloaded" seems to hop. 
- Is there any kind of a hover state?

**Comment by ntoll** [comment]
@ninavizz OK lets chat about this on Slack. :-)

**Comment by ntoll** [comment]
@creviera by out of alignment do you mean they don't have the same width from before and afterwards..?

**Comment by ntoll** [comment]
FWIW, I've not actually changed the spacing / layout of anything yet. I've just updated the icon on the button to the "spinner". So this out-of-alignment problem is probably already there before this PR was submitted. Happy to fix though, just need to know what you want. :-)

**Comment by ntoll** [comment]
Also, (sorry for the number of message) the colour changes are what were defined in the Zepelin page I linked to. I agree, the colour looks "nicer" if it remains the same as the "DOWNLOAD" link. But I'm a programmer, what do I know..? ;-)

**Comment by ntoll** [comment]
OK... so I've been looking into the layout of the file state as flagged by @creviera. It appears it was broken before this PR (current master displays this behaviour for me). I'm in the process of trying to clean this up.

**Comment by ntoll** [comment]
Whoop-de-do. This took a while to figure out... ;-)

(Note hoe everything is all aligned now...)

fixed

Happy to change anything. Just let me know if this looks OK to you.

**However** I *strongly* disagree with including a delay of a few seconds so people see the spinner. To my mind that's making the UI appear inaccurate to the user. If something's finished, I humbly suggest the UI should reflect that. :slightly_smiling_face:  After all, we want folks to *trust* this application right..? :scream:

**Comment by ntoll** [comment]
OK... borked some tests so fixing before I push.

**Comment by ntoll** [comment]
Please check again. Thanks!

**Comment by creviera** [comment]
> However I strongly disagree with including a delay of a few seconds so people see the spinner.

Whoops I meant we maybe shouldn't show the spinner if it's only spinning for a second because it's so fast it's confusing what happened.

**Comment by ntoll** [comment]
@creviera many apologies -- my misunderstanding.

I see what you mean. I don't know about you, but I sometimes find it infuriating if the computer flashes some important looking message up only for it to disappear immediately after you've registered there's an important looking message there and "dammit, what on earth did it say..?". ;-)

This is very much a case of helping the UI signal things in "human time" rather than the speedier "computer time". I guess we could schedule the change in UI state after something like 0.3 seconds, i.e. if the network latency is low and the file size is small, then it'll complete before then... BUT if there's a longer delay that's perceivable to the user, then the UI will look as if it's doing something.

I'll play around to see what I can do in this respect, but would welcome thoughts from more UX focussed folks with more experience and expertise than a numpty like me. :-) @ninavizz ???

**Comment by ntoll** [comment]
OK... I've just used a `QTimer.singleShot` to make this work + added tests. Feedback please. :-)

**Comment by ninavizz** [comment]
Hi @ntoll I'd like to get you permanent art for this spinner, but still do not know what format the art would need to be in. Could you let me know—and I'll create something straight away, for this PR and other animation needs? :D The timing concerns y'all discuss up above, I feel could be helpful to chat about synchronously before speaking to, here. Want to make sure I'm clearly understanding everyone/everything, first.

**Comment by creviera** [comment]
This is looking so good! I see you addressed issue 2 from my [review](https://github.com/freedomofpress/securedrop-client/pull/702#pullrequestreview-344244936), but it looks like issue 1 still exists:

one-issue

**Comment by ntoll** [comment]
@creviera fixed in latest push.

**Pull request merged**
