### PR TITLE
Localise dates shown in UI using QTimeZone

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
## Description

This PR includes the changes from #1626, except some formatting changes that weren't related to the topic of the PR.

**Why?**: We think those changes were introduced when trying to meet the linting criteria, and probably have their origin in differences between @philmcmahon development environment and the Circle CI testing environment.
Since we're about to cut a new release of the SecureDrop Client, we made the call of merging these changes, and troubleshoot linting behavior later. 

_Please refer to #1626 for context and previous reviews!_

Closes #1626

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
For future reference, https://github.com/freedomofpress/securedrop-client/pull/1636/commits/110c1a4cedf75b416deddeedca1147e63dc6c7ea is the only change with relation to #1626.

I'll rebase this PR onto the latest `main` now.

**Comment by gonzalo-bulnes** [comment]
(rebased without changes)

**Comment by gonzalo-bulnes** [comment]
(rebased once more onto the latest `main`, because no futher changes are expected there — the comparison link [above](https://github.com/freedomofpress/securedrop-client/pull/1636#issuecomment-1461027964) remains valid)

**Review by cfm — APPROVED** [review]
Thanks so much for following up, @philmcmahon, and for linting the linting, @gonzalo-bulnes.  :-)  This works as expected from #1626, the diff from which I've also reviewed visually.

Thank you for this contribution, @philmcmahon!

**Comment by philmcmahon** [comment]
Thanks @cfm and @gonzalo-bulnes !! @gonzalo-bulnes I've added you with write access to our fork in case it saves time in future.

**Comment by gonzalo-bulnes** [comment]
Thanks @philmcmahon! I got the invite, I'll accept it now 🙂

**Pull request merged**
