### PR TITLE
Incremental loading of the conversations

### LINKED ISSUE #984: improve performance for many submissions per source
On first start of the client, we add widgets for each item in the conversation view when we click on the source for the first time. If there are thousands of messages/files/replies per source, there will be a delay / the UI will be blocked as found with the SourceList in #846.

We should implement a similar fix as https://github.com/freedomofpress/securedrop-client/pull/944 to improve performance when adding widgets to the ConversationView.

### PR DESCRIPTION
**Pull request by kushaldas**
# Description

Fixes #984

The tests are failing. Tips anyone on how to fix those?

The functional tests are passing individually, but not in a group. We have to find the reason.

# Test Plan

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [ ] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/master/files/usr.bin.securedrop-client)
 - [ ] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

### CODE REVIEW

**Comment by kushaldas** [comment]
The functional tests are failing when I am trying to run them together, each test pass individually.

```
  tests/functional/test_delete_source.py::test_delete_source_and_their_docs PASSED                                                                       [  6%]
tests/functional/test_download_file.py::test_download_file PASSED                                                                                      [ 13%]
tests/functional/test_export_dialog.py::test_export_dialog PASSED                                                                                      [ 20%]
tests/functional/test_login.py::test_login_ensure_errors_displayed PASSED                                                                              [ 26%]
tests/functional/test_login.py::test_login_as_journalist PASSED                                                                                        [ 33%]
tests/functional/test_login_from_offline.py::test_login_from_offline Fatal Python error: Aborted

Thread 0x00007f23ce7fc700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23ceffd700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23d5e23700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23d6624700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23cffff700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23f09c3700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23f2e76700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Thread 0x00007f23f3677700 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/queue.py", line 170 in get
  File "/home/kdas/code/securedrop-client/securedrop_client/queue.py", line 113 in process

Current thread 0x00007f2415847740 (most recent call first):
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/tokens.py", line 4 in __init__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/scanner.py", line 599 in fetch_value
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/scanner.py", line 223 in fetch_more_tokens
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/scanner.py", line 116 in check_token
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/parser.py", line 428 in parse_block_mapping_key
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/parser.py", line 98 in check_event
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 127 in compose_mapping_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 84 in compose_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 133 in compose_mapping_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 84 in compose_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 133 in compose_mapping_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 84 in compose_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 111 in compose_sequence_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 82 in compose_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 133 in compose_mapping_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 84 in compose_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 55 in compose_document
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/composer.py", line 36 in get_single_node
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/constructor.py", line 41 in get_single_data
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/yaml/__init__.py", line 114 in load
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/vcr/serializers/yamlserializer.py", line 11 in deserialize
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/vcr/serialize.py", line 36 in deserialize
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/vcr/persisters/filesystem.py", line 15 in load_cassette
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/vcr/cassette.py", line 333 in _load
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/vcr/cassette.py", line 162 in load
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/vcr/cassette.py", line 86 in __enter__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pytest_vcr.py", line 87 in vcr_cassette
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 775 in call_fixture_func
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 949 in pytest_fixture_setup
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 900 in execute
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 571 in _compute_fixture_value
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 490 in _get_active_fixturedef
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 474 in getfixturevalue
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pytest_vcr.py", line 46 in _vcr_marker
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 779 in call_fixture_func
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 949 in pytest_fixture_setup
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 900 in execute
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 571 in _compute_fixture_value
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 490 in _get_active_fixturedef
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 474 in getfixturevalue
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 464 in _fillfixtures
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/fixtures.py", line 291 in fillfixtures
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/python.py", line 1427 in setup
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 366 in prepare
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 118 in pytest_runtest_setup
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 201 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 229 in from_call
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 201 in call_runtest_hook
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 129 in call_and_report
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 89 in runtestprotocol
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/runner.py", line 80 in pytest_runtest_protocol
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 92 in pytest_runtest_protocol
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/main.py", line 256 in pytest_runtestloop
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/main.py", line 235 in _main
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/main.py", line 191 in wrap_session
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/main.py", line 228 in pytest_cmdline_main
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 90 in main
  File "/home/kdas/code/securedrop-client/venv/lib/python3.7/site-packages/pytest.py", line 101 in <module>
  File "/usr/lib/python3.7/runpy.py", line 85 in _run_code
  File "/usr/lib/python3.7/runpy.py", line 193 in _run_module_as_main
Aborted
``` 

A few unit tests are also failing as we are trying to check the number of items in the conversatino view too early (before they get displayed). Any tips on how to fix these will be helpful.

**Comment by eloquence** [comment]
Deferring to near-term backlog as it's not been a significant issue for pilot installs so far. We'll revisit this in the next sprint (after the current 4/22-5/6 sprint), at the earliest.

**Comment by eloquence** [comment]
This doesn't seem like a likely performance optimization target in the near future so I'd be in favor of closing this PR - @kushaldas @creviera thoughts?

**Comment by creviera** [comment]
I think the reason tests are failing is because of the scheduler. We actually don't have great tests around the scheduler used for `add_source` for the same reason it's hard to do here. If you look at tests around `add_source` they just check that certain functions are called rather than that the SourceList contains the new sources after the cal to `add_source`. That's because it's done on a separate thread and we'd have to wait until the thread is finished before checking that the source widget was created. we could cover this behavior with a unit test, but it would probably be easier to use a functional test.

Also I think when we create a new source widget is when we should create a new conversation widget. Rather than waiting until the source is selected before creating the conversation widget. Performance wise, this would be fine since we already use QTimer to create sources, so create the conversations with them wouldn't be costly. Because of this, I think we should close this PR and focus on reworkig the way we create conversations all together. That is, we should no longer delete and add widgets when a new source is selected. Let's just create conversation widgets when source widgets are created and hide/show when necessary.

**Comment by creviera** [comment]
> The optimization would be noticeable if there were ever hundreds of conversation widgets to draw for a single source (we should have some tests that show this and to give us a better idea of the numbers here).

I ran some manual tests, and here's what I see (N is the number of speech bubbles in a single conversation)

## master branch 

#### N=1000

The client is responsive.

#### N=10,000

The first time you select a source with 10,000 speech bubbles, the client is not responsive for 30 seconds while it creates the conversation.

If you select a source with 10,000 speech bubbles, the client is not responsive for 10 seconds while it creates the conversation.

## pr branch

#### N=1000

The client is responsive.

#### N=10,000

The first time you select a source with 10,000 speech bubbles, the client is not responsive for almost 2 minutes while it creates the conversation.

Subsequent times you select this source, the client is not responsive for around 25 seconds while it recreates the conversation.

## About the results

The client is surprisingly less responsive with this change. I see that you chose 16 as the maximum slice size, which could be tweaked to improve performance:

```py
new_slice_size = min(16, slice_size * 2)
```

However, since the client is responsive with a thousand message items, I think we should hold off on working on an optimization for now. I think we have a scalability test improvement ticket somewhere that would probably be best to focus on first before picking this back up again.

What do others think?

**Comment by eloquence** [comment]
> However, since the client is responsive with a thousand message items, I think we should hold off on working on an optimization for now.

Having argued for a while that we should put this PR on ice, I agree with this. ;-)

**Comment by eloquence** [comment]
We discussed at standup today and agreed to close this out per discussion above.

**Pull request closed without merging**
