### PR TITLE
Preview last message in source list.

### LINKED ISSUE #135: Preview most recent message or reply in source view
Below the source designation, the source list should show a preview (text abbreviated with "..." if necessary) of the most recent message or reply, as shown in this grayscale wireframe:

snippets

If the most recent interaction is a message from the source, it should show an excerpt of that message; if the most recent interaction is a reply from the journalist, it should an excerpt of the reply.

If the most recent interaction is a file upload, we should show the most recent message or reply.

If there has never been any message or reply but only a file, we can show "_&mdash;submitted a file, no message&mdash;_".

### PR DESCRIPTION
**Pull request by ntoll**
# Description

Fixes #135.

The UI elements were already there. This was simply a plumbing task. I tried various approaches but this is the simplest one. The result looks like this:

latest_message_preview

**NOTE** The "not yet available" messages on initial start are cleared when the client refreshes (see screenie above). I did try to connect signals to make this work "automagically" but the code was messy and then I remembered that we're going to make the client update automatically after N-seconds in an upcoming change (i.e. the default behaviour of the client app will ensure the "not yet available" messages will update to the real content of the messages). Trust me, I much prefer this simpler approach. ;-)

One other thing, I've added `__str__` methods to the `db` based classes this touches on, since we re-use the "show me the content of this message" type behaviour in several places now and the object itself should probably be the arbiter of the default means of working out what such a string value should be.

# Test Plan

Added unit tests.

**NOTE** Hmm... the existing tests of `repr` I found **don't actually test anything**. They just run code which means the coverage check passes. I've followed this same approach for testing the new `__str__` methods mentioned above, since this appears to be a convention. However, I don't feel this is a good convention. Surely tests should `assert` something should be the case..? ;-)

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [X] These changes should not need testing in Qubes

If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to be updated. Please check as applicable:

 - [ ] I have submitted a separate PR to the [packaging repo](https://github.com/freedomofpress/securedrop-debian-packaging)
 - [ ] No update to the packaging logic (e.g., AppArmor profile) is required for these changes
 - [ ] I don't know and would appreciate guidance

### CODE REVIEW

**Comment by ntoll** [comment]
FYI CI fails are due to `install-deps` borking during build process. :-/ Any idea what's going on. This sometimes works and sometimes fails.

**Comment by redshiftzero** [comment]
thanks for flagging, that's due to a change that we made yesterday (i.e. unrelated to the diff here), am working on fixing over in #699

**Comment by ntoll** [comment]
@redshiftzero :+1:

**Comment by ntoll** [comment]
@creviera :+1: Thanks... I'll address the filename update points you raise. :-)

**Comment by ntoll** [comment]
@creviera fixed.

**Pull request merged**
