### PR TITLE
Migrate dependency management to poetry

### PR DESCRIPTION
**Pull request by legoktm**
* _Depends on https://github.com/freedomofpress/securedrop-client/pull/1674_

# Description

Switch dependency management to use poetry, which is much nicer than pip-tools. This is largely based off of
<https://github.com/freedomofpress/securedrop-proxy/pull/122> and applies the same changes to the Makefile and CI.

The main difference is that we install PyQt5 via system packages, so the two versions we specifically need are listed in pyproject.toml and vary on the Python versions shipped with bullseye and bookworm.

# Test Plan

* [x] CI passes
* [x] Running `make test`, etc. all works fine
* [ ] Building a package locally works
* [x] GH admin has removed `check-testing-requirements-bullseye` check requirement
* [x] https://github.com/freedomofpress/securedrop-builder/pull/474 has been merged and the reference to it in .circleci/config.yml removed

# Checklist

 - [x] These changes should not need testing in Qubes
 - [x] No update to the AppArmor profile is required for these changes
 - [x] No database schema changes are needed

### CODE REVIEW

**Comment by legoktm** [comment]
Going to switch this back to draft mode because it's blocked on https://github.com/freedomofpress/securedrop-builder/pull/474.

**Comment by legoktm** [comment]
One dependency cleared and another appears...now depends on https://github.com/freedomofpress/securedrop-client/pull/1674.

**Comment by zenmonkeykstop** [comment]
- CI and makefile targets look good
- The package builds, is ~2x larger than current prod one, diffoscoping shows it has both pip3.11 and pip 3.9 in the venv which a) weird and b) probably starts to explain the size difference
- gonna install in a dev setup and see how it looks.

**Review by zenmonkeykstop — DISMISSED** [review]
Visual review looks good, client package builds and is installable. LGTM!

**Review by zenmonkeykstop — DISMISSED** [review]

**Review by zenmonkeykstop — DISMISSED** [review]
One more time LGTM!

**Review by zenmonkeykstop — APPROVED** [review]
3rd time's the charm!

**Pull request merged**
