### PR TITLE
Refresh conversation view

### LINKED ISSUE #107: Automatically refresh conversation view after message downloads and decrypts
As messages and replies complete their download/decryption, we should redraw the conversation view for the current source so that we don't need to wait for a sync/refresh.

### PR DESCRIPTION
**Pull request by redshiftzero**
Closes #107

# Test plan

1. Login to client
2. Click on source in sidebar
3. The messages and replies are downloading... wait six seconds
4. The messages and replies should appear decrypted in the conversation view. The user should not have to sync again or take any other manual action

### CODE REVIEW

**Comment by heartsucker** [comment]
Ah ok so couldn't we pass the `gpg_dir` or something as a var and set it with `--homedir` if we're not in Qubes? Otherwise people are going to have to add it to their keyring anyway.

**Comment by redshiftzero** [comment]
we could make the following change:

in run.sh, if we're NOT on qubes we:
- add test key to a new dir: `$SDC_HOME/gpg`

if we are on qubes we:
- do not add the test key
- run the client without the `--no-proxy` arg

this does mean that in the decrypt functionality that is on master, we must pass through `--homedir $SDC_HOME/gpg` if we're using a temporary home directory, else we do not pass through a homedir

**Comment by redshiftzero** [comment]
since the changes requested here related to the dev env, I propose we track and do in a followup

**Comment by redshiftzero** [comment]
heads up some of these dev env changes (e.g. importing the test key during run.sh) was implemented by josh over in the replies branch (#67)

**Pull request merged**
