### PR TITLE
Refactor move generic widgets to 'gui.base' namespace

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
# Description

This is the 2nd step to be split out of #1369.

I made a mistake in https://github.com/freedomofpress/securedrop-client/pull/1377, the generic widgets ("base widgets") shouldn't be part of the same package that exposes the public GUI API. I realized that mistake as I was moving the `LoginDialog` to `auth`.

# Test Plan

- [ ] Confirm the widgets definition hasn't changed
- [ ] Confirm that the UI behavior/aspect haven't changed (e.g. the Source starring buttons depend on `SvgToggleButton`, the Source "papeclip" depends on `SvgLabel`, the "user button" in the side bar menu depends on `SvgPushButton`, the reply placeholder depends on `SecureQLabel` and the "Sign In" button depends on `SDPushButton`.)
- [ ] Confirm that the CI build is green

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [x] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `main` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [x] No database schema changes are needed

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
@creviera Before merging this PR, let's talk about signatures. It seems that the author signature gets stripped when merging without a merge commit, resulting in an unsigned commit in `main`. We could put extra attention on this one and see if we can merge while preserving the signatures on the commits that introduce diffs. (The automated merge commit should be empty because we update/rebase out branches before merging.)

**Review by rocodes — APPROVED** [review]
- [x] Tests pass
- [x] Everything looks sensible on visual review 
- [x] Client behaviour (testing in dev vm) looks the same (note: as a reviewer it would be extra helpful to have a little more detail about which visual components to pay close attention to in the test plan)

**Comment by gonzalo-bulnes** [comment]
> note: as a reviewer it would be extra helpful to have a little more detail about which visual components to pay close attention to in the test plan

Good point. Top of mind, the Source starring buttons depend on `SvgToggleButton`, the Source "papeclip" depends on `SvgLabel`, the "user button" in the side bar menu depends on `SvgPushButton`, the reply placeholder depends on `SecureQLabel` and the "Sign In" button depends on `SDPushButton`.

**Review by conorsch — APPROVED** [review]
Reviewed with @rocodes & @gonzalo-bulnes today. Diff is quite small and entirely unobjectionable. Onward!

**Pull request merged**
