### PR TITLE
Update wheel checksums after rebuilding for Bookworm / 3.11

### PR DESCRIPTION
**Pull request by legoktm**
# Description

See <https://github.com/freedomofpress/securedrop-builder/pull/412>.

Unblocks https://github.com/freedomofpress/securedrop-client/pull/1621

# Test Plan

* Using the above-linked PR, a build on bookworm passes.

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [x] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `main` and confirmed that the migration is [self-contained] and applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [x] No database schema changes are needed

[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-migrations

### CODE REVIEW

**Review by gonzalo-bulnes — DISMISSED** [review]
The hashes match the ones in https://github.com/freedomofpress/securedrop-builder/pull/412/files#diff-6625cb183d2ee3f777421db80705c3755676a1c8efa27247f05da626d16d0e7eR7

**Comment by gonzalo-bulnes** [comment]
Merging with a red Bookworm build, see https://github.com/freedomofpress/securedrop-builder/pull/412#issuecomment-1414526307 for details.

**Comment by gonzalo-bulnes** [comment]
@legoktm Why would the hashes have changes under Bullseye? ([failed job](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/3151/workflows/e05673cd-913d-4575-8a5e-d14a6247ace2/jobs/20238/parallel-runs/0/steps/0-104))

**Comment by legoktm** [comment]
The bullseye hashes haven't changed, that's just the diff between the requirements in this PR and what is currently in the securedrop-builder repository (without my PR there).

For example, looking at
```diff
-markupsafe==2.0.1 --hash=sha256:e61445980f0dcd584d728844d8ad516c9e460bd71f53c14c0269d73de6fba6be --hash=sha256:9a055a175f351a559937fb80ebb2885d005283577a016c0139817e261fb759eb
+markupsafe==2.0.1 --hash=sha256:bb3e541812095075336bcd935bb58941aedc0a7cba3c73d301dfdfd4d66a4eec --hash=sha256:7b12b29ae39060c29ed0d8cb1052fa1672832b5096f859fd35e896ca3b04ddd3 --hash=sha256:9a055a175f351a559937fb80ebb2885d005283577a016c0139817e261fb759eb
```

The first line shows:
e61445980f0dcd584d728844d8ad516c9e460bd71f53c14c0269d73de6fba6be is the new Python 3.11/bookworm wheel, 9a055a175f351a559937fb80ebb2885d005283577a016c0139817e261fb759eb is the pre-existing Python 3.9/bullseye wheel.

The second line shows:
bb3e541812095075336bcd935bb58941aedc0a7cba3c73d301dfdfd4d66a4eec is the old Python 3.10/bookworm wheel, 7b12b29ae39060c29ed0d8cb1052fa1672832b5096f859fd35e896ca3b04ddd3 is the old Python 3.7/buster wheel, and 9a055a175f351a559937fb80ebb2885d005283577a016c0139817e261fb759eb is the same pre-existing Python 3.9/bullseye wheel.

So the bullseye hash is the same, only the bookworm one changed, and the buster one was removed.

**Comment by gonzalo-bulnes** [comment]
Mmm, I see both. I misread that thr first time around, thanks for the detailed reply @legoktm.

**Edit**: I know what happened: I was looking at the diff in CI and read it backwards. I expected the new hashes on the `+` side, which on reflection was the wrong expectation. With that cleared, I'm merging.

**Comment by gonzalo-bulnes** [comment]
Argh, I keep forgetting: since the `build-bullseye` is required, we still can't merge because of the repo policies. (That are overly restrictive IMO -I'll say it once more 🤷‍♀️- precisely because of cases like this one: we have good reasons to want to do things in a given order and the policies remove our agency without bringing actual safety in return.)

**Comment by gonzalo-bulnes** [comment]
Not quite green yet here ([error](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/3151/workflows/a6713ab3-ef2e-48d3-821c-5ae53eec547a/jobs/20599)):

````
   × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      sys.argv ['/tmp/pip-install-w69400jw/ruamel-yaml-clib_987fb2fc8bca45b48024af423079519c/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-73oycv5k']
      test compiling /tmp/tmp_ruamel_owdl3bt0/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_owdl3bt0/test_ruamel_yaml.c
      Exception: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
````

**Comment by legoktm** [comment]
For some reason it's trying to install ruamel.yaml.clib from source instead of using the cp11 manylinux wheel (https://pypi.org/project/ruamel.yaml.clib/#files)....wonder if we're just missing the hash.

**Comment by legoktm** [comment]
Of course there's more...

* multidict - 3.11 support came in 6.0.3, but we should go to 6.0.4 since it has a bugfix (https://github.com/aio-libs/multidict/blob/master/CHANGES.rst)
* pyqt5-sip - 3.11 support came in 12.11.0, there's also a newer 12.11.1. I think this is supposed to match https://tracker.debian.org/pkg/pyqt5-sip ? which has 12.11.1.
* yarl - 3.11 support came in 1.8.2 (https://github.com/aio-libs/yarl/blob/master/CHANGES.rst)

**Comment by gonzalo-bulnes** [comment]
I've verified that the newly scoped check of testing requirements fails as expected when, say, the ` dev-bookworm-requirements.txt` file is not up-to-date ([example failing job](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/3177/workflows/b34ce9fd-e96e-4d68-90b4-035da0de5def/jobs/20752)).

**Comment by gonzalo-bulnes** [comment]
@legoktm Over to you, I'll leave an approval, and let you review my changes + merge :slightly_smiling_face: 

_Note that your last commits are not signed. :lock_with_ink_pen:_

**Review by gonzalo-bulnes — APPROVED** [review]
Good to go as far as I can tell, but I'll let you confirm and merge @legoktm! :football:

**Comment by legoktm** [comment]
Awesome, LGTM! (I can't "approve" since this is technically my PR)

**Pull request merged**
