### PR TITLE
Remove unnecessary work around segfaults in test suite

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
## Description

:crystal_ball: **Reviewers** ~rebase this branch once https://github.com/freedomofpress/securedrop-client/pull/1524 is merged, only the last few commits need review~ just :green_heart: :smile: 

Takes advantage of the thread management fixes in #1524 and removes the functional test script. (It is no longer needed as a segfault workaround because the segfaults causes were fixed.)

<details><summary>Obsolete comments, kept for historical reference</summary>

Also attempts to make the functional test suite a little bit faster by taking inspiration in the integration tests setup.

:parrot: Some of this is up for discussion, please express your preferences and thoughts as your review! :speech_balloon:

Two distinct trade-offs to discuss:

- **Running the functional tests independently** 
  - allows to make sure they are indeed independent
  - allows to run them concurrently (e.g. we run the integration tests in 4 concurrent workers) and decrease running time (~6.5 to ~5min)
  - requires either _adjusting the timeout times_ OR _relaxing the `flaky`_ parameters a little (`max_runs=4` seems to give a fair margin as per my testing)
- **Splitting the CI build steps**:
    - Trades off decreasing  _wall time_ (the actual time we wait on the build, ~6.5 to ~4min)  with increasing CPU time (the actual electricity our build consumes :zap: ~6.5 to ~12min in my testing, but we can make it ~11min easily - the longest task, unit testing takes 3.5min anyway, so we can group two that take 1.5min and save some CPU time) :framed_picture: 
<details><summary>:framed_picture: Preview of the CI build steps split (:warning: in a best-case scenario...)</summary>
Comparison of the CI build steps, before and after splitting them.</details>
</details>

## Test Plan

- [ ] Confirm that CI is green, ideally a few times in a row :green_apple: :green_apple: :green_apple: 

### Qubes OS environment    
     
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes OS testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes OS is required. Please make sure you mention it in the **tests plan**.
     
### AppArmor profile    
     
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please make sure you mention it in the **tests plan**.
     
### Database migrations    
     
If these changes modify the database schema, you should include a database migration. Testing that the migration applies cleanly on the `main` branch is necessary. Please make sure you mention it in the **tests plan**.

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
I'm marking this PR as "ready for review" as a call for comments. :slightly_smiling_face:

**Comment by gonzalo-bulnes** [comment]
Given #1546 I'll review this, update and see where that leaves us.

**Comment by gonzalo-bulnes** [comment]
I ran the pipeline 4 times in a row, without observing any flaky failures. :green_apple: :green_apple: :green_apple: :green_apple: 

This change also shaves 80 seconds from the functional test job, out of 200. :relaxed: 
We're now often running the entire pipeline in under 2min. :dancers: 

@rocodes @creviera We're ready to review!

**Comment by gonzalo-bulnes** [comment]
(rebased without changed to include new CI check)

**Review by legoktm — APPROVED** [review]
Nice!

**Pull request merged**
