### PR TITLE
update reply sender name during sync if it has changed

### PR DESCRIPTION
**Pull request by creviera**
# Description

Towards https://github.com/freedomofpress/securedrop-client/issues/76

This depends on https://github.com/freedomofpress/securedrop-sdk/pull/125 which can be installed via `pip install --upgrade git+https://github.com/freedomofpress/securedrop-sdk@add-journalist-name-to-reply#egg=securedrop-sdk` but should not be merged until the sdk is updated.

# Test Plan

1. `pip install git+https://github.com/freedomofpress/securedrop-sdk@add-journalist-name-to-reply#egg=securedrop-sdk`
2. run `make test` and see all tests pass locally (they won't pass here until the sdk is updated)
3. log into the client
4. log into the journalist UI with a new journalist account
5. send a reply to a source as the new journalist.
6. wait until next sync then check local client db
   - [ ] verify local db shows an account for that new journalist in the users table
7. change first and last name of this new journalist account from the journalist UI
8. wait until next sync then check local client db
   - [ ] verify local db shows the new first and last names for the journalist in the users table
9. change first and last name to empty string from the journalist UI
10. wait until next sync then check local client db
    - [ ] verify local db shows updated first and last name
11. change username of the new journalist account from the admin UI
12. wait until next sync then check local client db
    - [ ] verify local db shows updated username

### CODE REVIEW

**Comment by creviera** [comment]
Note: We will see CI fail here with errors like the following until the sdk is updated:

```
E               AttributeError: 'Reply' object has no attribute 'journalist_first_name'
```

**Comment by creviera** [comment]
Dependent on https://github.com/freedomofpress/securedrop-client/pull/1138

**Review by emkll — COMMENTED** [review]
Thanks @creviera test plan is passing for me using locally built sdk, and visual review of the diff looks good
1. `pip install --upgrade git+https://github.com/freedomofpress/securedrop-sdk@add-journalist-name-to-reply#egg=securedrop-sdk`
- [x] run `make test` and see all tests pass locally (they won't pass here until the sdk is updated)
3. log into the client
4. log into the journalist UI with a new journalist account
5. send a reply to a source as the new journalist.
6. wait until next sync then check local client db
   - [x] verify local db shows an account for that new journalist in the users table
7. change first and last name of this new journalist account from the journalist UI
8. wait until next sync then check local client db
   - [x] verify local db shows the new first and last names for the journalist in the users table
9. change first and last name to empty string from the journalist UI
10. wait until next sync then check local client db
    - [x] verify local db shows updated first and last name
11. change username of the new journalist account from the admin UI
12. wait until next sync then check local client db

As you mentioned in the PR description, marking as blocked until https://github.com/freedomofpress/securedrop-sdk/issues/127 is closed, and we can include SDK 0.1.1 in the requirements file as part of this PR to get tests passing

**Comment by emkll** [comment]
securedrop-sdk 0.1.1 has been released in https://github.com/freedomofpress/securedrop-debian-packaging/pull/193 , this PR is now unblocked.

We should now be able to use this new version of the sdk in the requirements file, and after a rebase on latest `main` this will be ready for final review.

**Comment by creviera** [comment]
thanks for the review. sdk in the requirements files has been updated, so now you'll see ci pass and you can skip `pip install --upgrade git+https://github.com/freedomofpress/securedrop-sdk@add-journalist-name-to-reply#egg=securedrop-sdk` if you run through the test plan again.

**Review by emkll — APPROVED** [review]
Went through the test plan again using a locally built deb (including the sdk 0.1.1 wheel). Works as expected, visual diff also looks good to me. Thanks!

#### Test plan
1. built client deb on this branch using the sdk wheel from pypi mirror
2. log into the client
3. log into the journalist UI with a new journalist account
4. send a reply to a source as the new journalist.
5. wait until next sync then check local client db
   - [x] verify local db shows an account for that new journalist in the users table
7. change first and last name of this new journalist account from the journalist UI
8. wait until next sync then check local client db
   - [x] verify local db shows the new first and last names for the journalist in the users table
9. change first and last name to empty string from the journalist UI
10. wait until next sync then check local client db
    - [x] verify local db shows updated first and last name
11. change username of the new journalist account from the admin UI
12. wait until next sync then check local client db
    - [x] verify local db shows updated username

**Pull request merged**
