### PR TITLE
add more spacing between tear and other widgets

### LINKED ISSUE #1289: Very little whitespace between tear pattern and file widgets
File widgets for sources with no messages are very near the margin of the conversation area, without substantive padding.

tear-space

## Steps to reproduce

1. Create a source and sync with the client; keep the source session active
2. Delete files and messages in the client
3. Submit a new file as the source and sync with the client

## Expected behavior

Tear pattern appears above file with some whitespace between them

## Actual behavior

Objects are clustered together with little padding

### PR DESCRIPTION
**Pull request by creviera**
# Description

Fixes #1289

# Test Plan

1. Set up client with the following sources:
  * Source with one file widget 
  * Source with tear
  * Source with tear followed by one file widget
  * Source with tear followed by message or reply widget (for reference)
- [ ] Confirm spacing looks correct for each scenario above
2. Now add lots of messages, replies, and/or files until you can scroll for each scenario above
- [ ] Confirm no padding exists between conversation item widgets and the top/bottom of the scroll window 

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [x] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [ ] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `main` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [x] No database schema changes are needed

### CODE REVIEW

**Comment by eloquence** [comment]
This all looks good to me per test plan. I've observed an issue with counters in the deletion dialog, which is likely unrelated to these changes and which I'll file separately. 

I'm not sure that the tear pattern should be "sticky" when there is scrollable content. It could be confusing (what's "earlier" from the point of view of the messages that are rendered in the conversation view?). The last screenshot shows that this also results in situations where the tear pattern is very close to partially rendered message bubbles. But I think we can discuss that as a lower priority and potentially after this release, as well.

IOW, functionally, this PR looks great from my end :)

## Tear pattern followed by replies

tear_with_replies
## Tear pattern followed by message
tear_followed_by_message
## Tear pattern followed by file
tear_followed_by_file
## Source with single file
source_with_single_file
## Tear pattern is "sticky" when there is scrollable content
tear_sticky_no_padding

**Comment by creviera** [comment]
I can confirm that the file count is off on our `main` branch

**Comment by creviera** [comment]
> This all looks good to me per test plan. I've observed an issue with counters in the deletion dialog, which is likely unrelated to these changes and which I'll file separately.

Yup, it's on `main` so unrelated to this PR. Thanks for filing: https://github.com/freedomofpress/securedrop-client/issues/1307

> I'm not sure that the tear pattern should be "sticky" when there is scrollable content. It could be confusing (what's "earlier" from the point of view of the messages that are rendered in the conversation view?). The last screenshot shows that this also results in situations where the tear pattern is very close to partially rendered message bubbles. But I think we can discuss that as a lower priority and potentially after this release, as well.

I think some extra work went into making a sticky tear widget, so let's discuss more and make sure we know this is what we want/ don't want. I don't think it should hold up the release and also predict a bit of debate on this one.

**Comment by creviera** [comment]
looks like the test failures earlier were just flakes, so I think this is ready for @conorsch's final review

**Comment by conorsch** [comment]
Looks great. Prepared my instance as requested, and ran through the various scenarios. In all cases, the new, more spacious layout is easier on the eyes. Below are a few screenshots, but they don't add much to the discussion above, just submitting them as substantiation.

## Before fix (running latest nightly)
sdc-scrunched-repro

## After fix (running this branch)
sdc-scrunched-resolved

## Stickiness with long messages
This is the only case where things still look slightly crowded to me, but it's a quibble. Submitting a very long text message makes it easy to see that the tear sticks to top, as intended. 

sdc-still-a-bit-scrunched

## Stickiness with multiple messages
Rather than a single long message to force scrolling, multiple short messages also show stickiness of the tear pattern, as intended. The padding around the message boxes themselves keeps everything pleasantly readable. 

sdc-not-so-scrunched-after-all

**Review by conorsch — APPROVED** [review]
Looks great. Thank you, @creviera, for the fix, and thanks to @eloquence for the patience in reporting and testing!

**Pull request merged**
