### PR TITLE
Add black and isort

### LINKED ISSUE #1100: add black and isort formatting tools
After discussion we're going to try:
 - black with line length 100
 - isort

We'll add the tool-specific config in a new `pyproject.toml` file (unless any issues arise from its usage, if so add a note to this ticket). 

Commits doing this should be included in a new file `.git-blame-ignore-revs` so we can use `git blame --ignore-revs-file` (h/t to @rmol for pointing this out). That file isn't a default but it seems like a few other projects are using it e.g. Firefox so we can do the same.

### PR DESCRIPTION
**Pull request by rmol**
# Description

Adds the black and isort tools to the development requirements, and adds Makefile targets for both checking and applying them.

Fixes #1100.

# Test Plan

- Check out the first commit on `add-black-isort` with `git checkout 86ee815`
- Run `make check-isort`. It should show the changes it would make.
- Run `make check-black`. It should show the changes it would make.
- Check out the last commit: `git checkout add-black-isort`
- Rerun `make check-isort` and `make check-black`. No changes should be indicated.
- Run `git blame securedrop_client/logic.py | head -60 | grep -c 361ba88`. There should be 22 lines attributed to that revision.
- Run: 
  - `git config blame.ignoreRevsFile .git-blame-ignore-revs`
  - `git config blame.markIgnoredLines true`
  - `git config blame.markUnblamableLines true`
- Run `git blame securedrop_client/logic.py | head -60 | grep 361ba88`. There should be three lines attributed to that revision, each prefixed with an asterisk. This indicates that those changes are only attributable to the ignored revision.

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [x] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/master/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `master` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `master` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [x] No database schema changes are needed

### CODE REVIEW

**Comment by eloquence** [comment]
This is still blocked on the pypi.securedrop.org update, correct?

**Comment by rmol** [comment]
Technically not blocked -- the formatting changes can be verified -- but we do need to change the Debian package rules in [securedrop-debian-packaging](https://github.com/freedomofpress/securedrop-debian-packaging) before we can successfully package it.

**Comment by rmol** [comment]
Um, I should check CI before talking. Yeah, this isn't getting through CI until the packaging repo is updated. I'll see to that first thing in the morning.

**Comment by eloquence** [comment]
@rmol Flagging that this branch now has conflicts.

**Comment by rmol** [comment]
@eloquence Thanks, rebased.

**Comment by rmol** [comment]
And again. :neutral_face:

**Pull request merged**
