### PR TITLE
[wip] [ui polish] Reply pane styling

### LINKED ISSUE #539: Reply box accepts rich text input
The client currently accepts rich text input in the reply box, e.g., via copy and paste:

Screenshot from 2019-08-19 23-48-26

While such input will be filtered when sending a reply, it should not be accepted at all, i.e. the reply box should act similar to an HTML `<textarea>`, treating all input as plain text.

### PR DESCRIPTION
**Pull request by deeplow**
Do not merge. Waiting on discussion in https://github.com/freedomofpress/securedrop-client/pull/580#issuecomment-545320799

# Description
- Converts rich text into plaintext (reply box was accepting rich text input)
- add styling according to mockup

Fixes #539 and partially #572 

Before:
before

After:
reply-2

Objective: (mockup)
mockup

# Test Plan
1. copy rich text
2. paste it into reply box

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [x] These changes should not need testing in Qubes

# Comments
Considerations for future PRs:
  - keyboard shortcuts (ctrl+return) in discussion if should be implemented: https://github.com/freedomofpress/securedrop-client/issues/572
  - add rich text input (or alternative) only for placeholder "Compose a reply to **Source Name**"
  - think about the scrollbar (should it go away?)
  - Shouldn't the text scale with the content? (it might be hard to have 20% of the screen with an empty reply box when the journalist is reading messages) Discussion: https://github.com/freedomofpress/securedrop-client/issues/572

### CODE REVIEW

**Comment by deeplow** [comment]
Actually it might not be as simple as this because if we want to to the placehoder like <kbd>compose a reply to **Surreal Yo-Yo**</kbd>, it might require rich text but somehow get disabled.



 I will investigate this.

**Comment by deeplow** [comment]
> I will investigate this.

It was decided that this may go on another PR

**Comment by deeplow** [comment]
The client is cracking in offline mode. I'll check that later

**Comment by deeplow** [comment]
> The client is crashing in offline mode.

this has now been fixed and some styling to the offline mode was added as well as a placeholder for online mode with the tempory text "Compose a reply to Bold Sourcename"

**Comment by deeplow** [comment]
I've hidden the vertical scrollbar in the reply box even when the box is bigger than its size. 
@ninavizz let me know if this is something we want:

Before:

scroll-before


After:

scroll

**Comment by deeplow** [comment]
I'll fix the linting problem that is making the test fail on CI

**Comment by ninavizz** [comment]
Yes, thank you!! The little purple airplane should be a few pixels lower, though; it's lowest points should be flush with the baseline of the last line of text. Thank you, Deeplow!

**Comment by deeplow** [comment]
> The little purple airplane should be a few pixels lower, though; it's lowest points should be flush with the baseline of the last line of text

Like this? (the image below is the mockup)
spec

The only problem now is that it crops the last line in half.

Also, @ninavizz I would also like some feedback on the airplane in offline mode. Quoting from [the issue](https://github.com/freedomofpress/securedrop-client/issues/572#issuecomment-545286140)

> I didn't see any mockups for the offline mode, so I just did what I thought made sense.
> 
> The current version looks like this: (over in #580)
> 
> offline
> 
> @ninavizz I think we should also add a disabled-looking airplane. What do you think? (it the last iterations of the code there were none). With the plane disabled it would look like:
> 
> plane-disabled
> 
> I already have the code for that which I can merge into #580, in case that's the way to go.

**Comment by deeplow** [comment]
I'll be trying to add the source name in the reply box

**Comment by deeplow** [comment]
@creviera could you check if the test I did looks sane?

I had to make select a source from the sources list. Otherwise, I think it would be always true since I'd be creating a source and using that for a ReplyBoxWidget and testing the placeholder.

**Comment by deeplow** [comment]
> Also, currently when clicking inside the textbox the `Compose a reply` text does not go away as I expected. Instead it goes away when you start typing, but I think it's distracting having the text in front of the cursor as you're thinking about what to type. It would be great if you could update this behavior as part of this PR as well.

@creviera regarding this, It's intended Qt behavior and there doesn't seem to be a default way to disable that. We might have to find another way, but let's do that in another PR, I think.

From the docs (https://doc.qt.io/qt-5/qtextedit.html#placeholderText-prop)
>placeholderText : QString
>
>This property holds the editor placeholder text
>
>Setting this property makes the editor display a grayed-out placeholder text **as long as the document() is empty.**

**Comment by creviera** [comment]
> @creviera could you check if the test I did looks sane?
> 
> I had to make select a source from the sources list. Otherwise, I think it would be always true since I'd be creating a source and using that for a ReplyBoxWidget and testing the placeholder.

I think your test looks good, although to improve code clarity, you could change A->B:

A:
```py
    sl = SourceList()
    sl.setup(controller)
    ...
    source_1 = factory.Source()
    source_2 = factory.Source()
    sl.update([source_1, source_2])
    source_1_item = sl.item(0)
    source_2_item = sl.item(1)
    ...
    sl.setCurrentItem(source_2_item)
    selected_source = sl.itemWidget(sl.currentItem()).source
    rb = ReplyBoxWidget(selected_source, controller)
    assert rb.text_edit.placeholderText().find(source_2.journalist_designation) != -1
```

B:
```py
    source = factory.Source()
    rb = ReplyBoxWidget(source, controller)
    assert rb.text_edit.placeholderText().find(source.journalist_designation) != -1
```

Because all you're really testing is that the journalist_designation used in the placeholder text matches the journalist_designation of the ReplyBoxWidget source.

The rest of your test is better done at the `SourceConversationWrapper` level. That's where we do things like making sure the `ReplyBoxWidget` is initialized with the currently selected source whenever selection changes in the `SourceList` etc.

**Pull request merged**
