### PR TITLE
Align star -> source name -> paperclip in source list item.

### LINKED ISSUE #523: Update star icon
# Description

- star should be vertically centered with source name
- replace star with inventory list star

### PR DESCRIPTION
**Pull request by ntoll**
# Description

Fixes #523.

# Test Plan

@ninavizz checks and confirms (or else tells me what to fix).

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [X] These changes should not need testing in Qubes

If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to be updated. Please check as applicable:

 - [ ] I have submitted a separate PR to the [packaging repo](https://github.com/freedomofpress/securedrop-debian-packaging)
 - [X] No update to the packaging logic (e.g., AppArmor profile) is required for these changes
 - [ ] I don't know and would appreciate guidance

### CODE REVIEW

**Comment by eloquence** [comment]
@ntoll In the issue description it notes:

> replace star with inventory list star

But I don't see an icon change here. I believe "inventory list star" refers to [this star icon](https://github.com/freedomofpress/securedrop-ux/issues/17#issuecomment-472163715).

**Comment by ntoll** [comment]
@eloquence I'm so sorry... yup, I missed that one. Fixing now.

**Comment by ntoll** [comment]
OK... I notice the colours in @ninavizz's original spec (to which you link) are different to the ones mentioned in the original ticket. I've gone with @creviera's colours since they were specified most recently.

**ALERT** it appears that the new SVGs don't work well with the highlighting / shadow on mouse over. Any advice on what that's supposed to do would be awesome (see screenie):

star_update

**Comment by ntoll** [comment]
The original issue which has all the links that included the hover/mouse-over effects for the starring and plane send button is #415,  which I addressed in commit 0c91c88a.

**Comment by ninavizz** [comment]
@ntoll Created issue #873 to spec updated hover states for allthings, including this. From that issue:

> **8: Star w/in Source w/in Source List**
> 
> ON hover, background to #80e3ff
> Selected, background to #2a319d aka GrimaceBlue
> Unselected, background to ##d3d8ea aka unselected-star-blu

...however, when the Source Item is hovered-over in the Source List, a Star state change happens there, too:

> **4: Hover on Source w/in list**
> 
> Source name to filepane-blue
> Paperclip to filepane-blue
> Date to filepane-blue
> Background to #f1fcfe
> Star to get white dropshadow of box-shadow: 0 0 3px 0 #ffffff;

Both of the above, reference [this Zeplin](https://zpl.io/V0g0MlE).

**Comment by ntoll** [comment]
@ninavizz here's a screenie for you:

star_states


Getting the star to change on hover took a bit of figuring out because Qt CSS isn't like HTML CSS. In any case, I think it works as you suggest except for one aspect, I'm not sure what you mean "Hover on Source w/in list" where you describe a drop shadow on the star -- the Zeplin you link to doesn't actually show this. Drop shadows are a PiA to get right on Qt... can this be a "nice to have"..? ;-)

**Comment by ninavizz** [comment]
Delighted! Yes, for this PR everything looks marvelous to me! :)

The other things you noted, are for separate PRs. I'll speak to them directly, in the Issue.

**Pull request merged**
