### PR TITLE
Improve scrolling logic in conversation view

### LINKED ISSUE #144: Message panel scrolls to the bottom after downloading a submitted file, possibly moving the file entry out of view
If a message thread has a downloaded file at the beginning, and the user clicks Download, the message panel is redrawn once the file is downloaded and decrypted, scrolled all the way to the bottom. 

If the thread is longer than can be displayed all at once, this means that the thread appears to jump down to the bottom messages, putting the file that was just downloaded out of view.

It would probably be better for the message thread to be redrawn at the same point as it was when the user clicked Download.

### PR DESCRIPTION
**Pull request by deeplow**
## Status
Work in progress (tests missing)

## Description of Changes

Fixes #144 is a way that is simple enough. Structural changes are still needed for #187 but for the time being this solves the issue.

renamed `move_to_bottom` function in `widgets.py` to `update_conversation_position` as it does not always go to the bottom. Added checks to see what parts of the conversation are currently visible. The way it works currently is it detects whether or not it is within a view-port distance of the last message (since it is hard to detect exactly the length of the last message)

## Testing
Open conversation with source. Type enough text such that it covers more than the window. Pull to the top and receive a msg from the source. It should stay in the same place. move to the bottom and do the same and see that it scrolls with the new content.

Type any message as a journalist and it should scroll to the bottom too

## Deployment
No deployment issues

## TODO
Testing needs to be redone for the function `move_to_bottom` as it was renamed and behavior change. I will do the test soon, but I will still have to learn how to do them. If someone with more experience would like to make a test, please feel free to. Otherwise it should take me a couple of days.

### CODE REVIEW

**Comment by deeplow** [comment]
@creviera There you go

**Comment by creviera** [comment]
This looks great @deeplow. And looks the test for `move_to_bottom` can be extended to test different values of `current_val`, `viewport_height`, and `max_val`. Writing the tests will no doubt take more time than the code change. I think this looks ready once test(s) are written! :rocket:

**Comment by deeplow** [comment]
@creviera cool. Thanks. I was working on the tests the other day but couldn't finish them, especially because the mocker value that I was creating was the same one I wanted to test:
```python
cv.scroll.verticalScrollBar().value = mocker.MagicMock()
# I was thinking we need this to fake that the scrollbar is at position 500 (away from the bottom)
cv.scroll.verticalScrollBar().value.return_value = 500

# then we update the position
cv.update_conversation_position(0, 6789)

# but later we also need to test what the scrollbar value was updated to
assert cv.scroll.verticalScrollBar().value() == 500
```
But this does not work because value is no longer part of the original code but a mocker object, rather.
I'll try to figure this out

**Comment by deeplow** [comment]
@creviera the above code is just a snippet. I had also some parts for simulating the `viewport_height`, `max_val` and `current_val`

**Comment by creviera** [comment]
The test before the change in this PR checked that the vertical scrollbar's setValue method was called with the expected value. That test is failing now with this error:
```python
...
>       if current_val + viewport_height > max_val:
E       TypeError: unorderable types: MagicMock() > int()

securedrop_client/gui/widgets.py:752: TypeError
```
I believe the `return_value`s for the mocked viewport and verticalscrollbar objects need to be set to avoid this `TypeError`. Maybe you could try something like:
```python
    cv.scroll.verticalScrollBar().value.return_value = 100
    cv.scroll.viewport().height.return_value = 100
```

**Comment by deeplow** [comment]
@creviera I have some questions

##### regarding naming:
*  `test_ConversationView_update_conversation_position_follow`
for testing the if the conversation is being followed when the scrollbar is near the bottom

* `test_ConversationView_update_conversation_position_stay_fixed`
and this one for when the scrollbar stays fixed because the journalist is reading something above

Are these names fine? (they might be quite long)

##### Regarding the values picked for testing
`cv.scroll.verticalScrollBar().value` is set to the limit where it will/won't scroll to the bottom on the respective test. Since there were so many possible values I decided to go to the edge cases. Do you think they are inclusive enough? Or should they be some other values?

**Comment by creviera** [comment]
+1 for descriptive test names. I personally prefer test names that are in the present tense, like:

`test_ConversationView_update_conversation_position_follow` -> `test_ConversationView_update_conversation_position_follows`
`test_ConversationView_update_conversation_position_stay_fixed` -> `test_ConversationView_update_conversation_position_stays_fixed`

But I don't think this is an agreed-upon style yet, so up to you.

The values you chose to test with lgtm!

**Pull request merged**
