### PR TITLE
Upgrade dependency: certifi

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
## Description

Routine upgrade.

## Test plan

- [x] Confirm that CI is green :green_apple: 
- [x] Confirm that the wheel hash matches one of those added in https://github.com/freedomofpress/securedrop-builder/pull/403

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
(rebased)

**Comment by gonzalo-bulnes** [comment]
Thanks @zenmonkeykstop ! I'll squash both commits. :+1:

**Review by gonzalo-bulnes — COMMENTED** [review]
- [x] Confirm that CI is green :green_apple: 
- [x] Confirm that the wheel hash matches one of those added in https://github.com/freedomofpress/securedrop-builder/pull/403

**Review by eaon — APPROVED** [review]
dev requirement hashes also include the upstream wheel hash, but the builder one looks fine, so merging!

**Pull request merged**
