### PR TITLE
stretch background of left pane

### PR DESCRIPTION
**Pull request by creviera**
# Description

Fixes https://github.com/freedomofpress/securedrop-client/issues/1209

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [ ] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [ ] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `main` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [ ] No database schema changes are needed

### CODE REVIEW

**Review by kushaldas — DISMISSED** [review]
Do you have any resolution limit? The first screenshot is from `main` branch. 

Screenshot from 2021-02-01 17-32-15


Next screenshot is from this PR.


Screenshot from 2021-02-01 17-33-42


@creviera is this the correct behavior? Maybe 2k was too much of a resolution.

**Comment by creviera** [comment]
oh interesting! great screenshots kushal - what you're seeing is also happening on the `main` branch and this PR should have fixed it. i'll look into what's going on here.

**Comment by eloquence** [comment]
(Given current sprint priorities, moving to top of backlog for now.)

**Comment by creviera** [comment]
Here's an update on my progress:

Before: 
Screenshot from 2021-03-22 18-42-15

After: 
Screenshot from 2021-03-22 18-41-45

In motion:
looks-good-until-next-slide-plz

Words:
You can see an example of how we can support transparent widgets on top of our branding barre in this PR by looking at the UserProfile widget. This will look nicer when we start adding more left pane widgets, but we have to make sure that the bg image isn't too noisy as we add more towards the darker hexes. 

The remaining thing left to do is to fix this:

svg-needs-more-height

The easiest thing might be to just edit the SVG so that the viewbox is taller (right now it's at 884px, and perhaps we just want to make it the largest size we plan on supporting for the client). But I think with two more custom widgets we can have the look we're going for here AND support an enormous client window (it's just a bit more complicated to do). :]

**Comment by creviera** [comment]
Okay this is ready

**Comment by eloquence** [comment]
Functionally this looks good to me! The scaling behavior is nicer even on smaller screen sizes (logo is always visible), and in portrait mode, it resolves #1209 for me as advertised.

# Before
Screenshot_2021-03-25_17-57-35

# After
Screenshot_2021-03-25_18-01-59

**Review by emkll — APPROVED** [review]
LGTM, works well with 3840 vertical pixels
Screenshot_2021-03-29_12-45-38

**Pull request merged**
