### PR TITLE
Make RunnableQueue process any QueueJob instead of just ApiJob

### PR DESCRIPTION
**Pull request by creviera**
# Description

Fixes https://github.com/freedomofpress/securedrop-client/issues/1444

This is a draft reply until https://github.com/freedomofpress/securedrop-client/pull/1434 is merged, which will create a conflict.

# Test Plan

Since this is a refactor-only, perform regression testing around the queue: 
* Cause a network outage to enqueue a `PauseQueueJob` and confirm that the behavior is the same as on `main`
* Send a reply
* Download a file
* Logout and log in again

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [ ] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [ ] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `main` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [ ] No database schema changes are needed

### CODE REVIEW

**Comment by cfm** [comment]
@creviera, would you like me to look at this in this sprint now that we've put #1434 on ice?

**Comment by creviera** [comment]
@cfm sounds good to me! I can get this ready for your review today.

**Comment by cfm** [comment]
Great, @creviera, and I can plan to review tomorrow.

You asked out of band if I would approach this any differently.  I agree with you that any `QueueJob` should accepted from `ApiJobQueue` to `RunnableQueue`!  My only question is whether we need explicit typing or processing logic to handle non-`ApiJob` `QueueJob`s (e.g., "control jobs" like the `PauseQueueJob`) that are valid on the queue but lack the `_do_call_api` method otherwise expected by `RunnableQueue.process()`.  Right now, if for example a `PauseQueueJob` slipped through changed logic in `process()`, it would raise an `AttributeError`, which would be less useful than having `QueueJob` implement `_do_call_api` just enough to raise a `NotImplementedError`.

**Comment by cfm** [comment]
That makes sense to me, @creviera!

**Review by cfm — APPROVED** [review]
@creviera, I know this is still in draft, but I've taken a look as we discussed earlier this week.  The changes in `RunnableQueue` look good and placate mypy!

Note that `ApiJobQueue` is still typed only in terms of `ApiJob`s.  I think that's right in the layering of the current implementation.  The lower-level or wide facility (`RunnableQueue`) takes instances of the lower-level or wide class (`QueueJob`s), while the higher-level or narrow facility (`ApiJobQueue`) takes only instances of the higher-level or narrow class (`ApiJob`s).  I hadn't recognized that symmetry before, precisely because of the typing, and I like that this change makes it explicit.

**Review by cfm — APPROVED** [review]
CI passes and manual testing shows no regressions, including during the suggested flows:


* [x] Cause a network outage to enqueue a `PauseQueueJob` and confirm that the behavior is the same as on `main`
* [x] Send a reply
* [x] Download a file
* [x] Log out and log in again

**Pull request merged**
