### PR TITLE
securedrop-client 0.2.0

### PR DESCRIPTION
**Pull request by redshiftzero**
# Description

If no issues are found with the latest securedrop-client nightly, 0.2.0 can be released along with its corresponding securedrop-proxy release: https://github.com/freedomofpress/securedrop-proxy/pull/74

# Test Plan

## Test plan below is a draft added by @eloquence on 2020-05-07

**Fix for #1033 (merged in #1045)** 
- [ ] Confirm that the baseline of filenames in the client is correctly aligned with Export/Print actions (i.e. [this minor rendering issue](https://user-images.githubusercontent.com/213636/78064524-bfbd9880-7346-11ea-93cc-ac23e05b3c85.png) should no longer occur)

**Fix for #1042 (merged in #1043)**
- [ ] Confirm that when performing the first sync of a client against a server with multiple sources, sources at the top of the list should have their messages and replies populated first. You should be able to see the progress of the sync as it works down through the source list.

**Fix for #1053 (merged in #1057) and increased sync timeout (merged in #1055)**
- [ ] Sync with a small number of sources to ensure that every 15 seconds you see an animation pulse. Test with a large number of sources (300+ range) to ensure that that long metadata syncs show a continuous sync animation.
- [ ] Confirm that there are no other regressions during these syncs.

**Fix for #1030 (merged in #1058)**
- [ ] Confirm that leading and trailing whitespace is trimmed from source messages and replies 

**Fix for #1052 (merged in #1063) and #1064 (merged in #1065)**
- [ ] Confirm that you can select the contents of individual messages or replies with the mouse (left-click).
- [ ] Confirm that you can use standard keyboard shortcuts (`Ctrl+C` and `Ctrl+V`) to copy and paste these messages within `sd-app`
- [ ] Confirm that this can be used as a workaround for #815 by submitting a very long source string (e.g., `0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789`) and selecting it.
- [ ] Confirm that right-clicking in the Conversation View has no effect
- [ ] *When testing with https://github.com/freedomofpress/securedrop-workstation/pull/533* Confirm that you can copy the contents of messages or replies to a VM tagged with `sd-receive-app-clipboard`

**Fix for #1060 (merged in #1069)**
- [ ] Observe that the logs for downloaded messages, replies and files no contain empty strings, and that the folder names in the logs are correct
- [ ] Observe that the logs do not include sensitive original filenames (e.g., an uploaded file `moscow.avi` should not appear in the logs under that name after the file is downloaded in the client)

**Fix for #140 (merged in #1059)**
- (Re-)start the client
- Before logging in, in `sd-gpg`, run `mv /home/user/.gnupg /home/user/.gnupg.save` to delete the submission key.
- Log in. 
- [ ] Confirm that messages and replies are gray and italic, containing decryption errors.
- Wait and watch the client log, confirming that messages and replies are never being retried because of the download failures.
- Back in `sd-gpg`, run `rm -rf /home/user/.gnupg && cp -ax /home/user/.gnupg.save /home/user/.gnupg`.
- [ ] Wait for the next sync; the failed downloads should not be retried and should not change their visual state, even though the key is now present.
- [ ] Restart the client. All the failed downloads should be retried, and the conversation views should update to normal status.

**Fix for #1051 (merged in #1071)**
-  (Re-)start the client
- While the login screen is displayed, copy some string into the clipboard, e.g., "asdf" or your password
- [ ] Observe that the string you copied can be successfully pasted multiple times
- Log into the client
- [ ] Observe that the string you copied can no longer be pasted into the reply box
- [ ] Verify that the clipboard is also purged when switching into offline mode instead of logging in

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [ ] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [ ] These changes should not need testing in Qubes
 - [x] These changes need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/master/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [ ] I have written a migration and upgraded a test database based on `master` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `master` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [x] No database schema changes are needed

### CODE REVIEW

**Comment by eloquence** [comment]
(Fleshing out test plan now based on `git log 0.1.6..master`.)

**Comment by eloquence** [comment]
I believe I've captured everything that's been merged since 0.1.6; feedback on draft test plan very much appreciated! Happy to curb level of detail or change organization in other ways. Note that this does _not_ yet fully cover the RPM-level changes; see https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests#securedrop-workstation-030 for a first outline of those.

**Comment by eloquence** [comment]
Some initial test results. In order to test, I switched my existing install (in all other respects currently configured in "production" mode) over to the securedrop-client and securedrop-proxy nightlies from `apt-test`.

**Fix for #1033 (merged in #1045)** 
- [x] Confirm that the baseline of filenames in the client is correctly aligned with Export/Print actions (i.e. [this minor rendering issue](https://user-images.githubusercontent.com/213636/78064524-bfbd9880-7346-11ea-93cc-ac23e05b3c85.png) should no longer occur)

**Fix for #1042 (merged in #1043)**
- [x] Confirm that when performing the first sync of a client against a server with multiple sources, sources at the top of the list should have their messages and replies populated first.
  - First all source messages populate top to bottom, then all replies populate top to bottom.

**Fix for #1053 (merged in #1057) and increased sync timeout (merged in #1055)**
  - [x] Sync with a small number of sources to ensure that every 15 seconds you see an animation pulse. 
  - [ ] Test with a large number of sources (300+ range) to ensure that that long metadata syncs show a continuous sync animation.
     - Not done yet
- [x] Confirm that there are no other regressions during these syncs.

**Fix for #1030 (merged in #1058)**
- [x] Confirm that leading and trailing whitespace is trimmed from source messages and replies 

**Fix for #1052 (merged in #1063) and #1064 (merged in #1065)**
- [x] Confirm that you can select the contents of individual messages or replies with the mouse (left-click).
- [x] Confirm that you can use standard keyboard shortcuts (`Ctrl+C` and `Ctrl+V`) to copy and paste these messages within `sd-app`
- [x] Confirm that this can be used as a workaround for #815 by submitting a very long source string  and selecting it.
- [x] Confirm that right-clicking in the Conversation View has no effect
- [ ] *When testing with https://github.com/freedomofpress/securedrop-workstation/pull/533* Confirm that you can copy the contents of messages or replies to a VM tagged with `sd-receive-app-clipboard`
  - Not tested yet

**Fix for #1060 (merged in #1069)**
- [x] Observe that the logs for downloaded messages, replies and files no contain empty strings, and that the folder names in the logs are correct
- [x] Observe that the logs do not include sensitive original filenames (e.g., an uploaded file `moscow.avi` should not appear in the logs under that name after the file is downloaded in the client)

**Fix for #140 (merged in #1059)**
- (Re-)start the client
- Before logging in, in `sd-gpg`, run `mv /home/user/.gnupg /home/user/.gnupg.save` to delete the submission key.
- Log in. 
- [x] Confirm that messages and replies are gray and italic, containing decryption errors.
- Wait and watch the client log, confirming that messages and replies are never being retried because of the download failures.
- Back in `sd-gpg`, run `rm -rf /home/user/.gnupg && cp -ax /home/user/.gnupg.save /home/user/.gnupg`.
- [x] Wait for the next sync; the failed downloads should not be retried and should not change their visual state, even though the key is now present.
- [x] Restart the client. All the failed downloads should be retried, and the conversation views should update to normal status.

**Fix for #1051 (merged in #1071)**
-  (Re-)start the client
- While the login screen is displayed, copy some string into the clipboard, e.g., "asdf" or your password
- [x] Observe that the string you copied can be successfully pasted multiple times
- Log into the client
- [x] Observe that the string you copied can no longer be pasted into the reply box
- [x] Verify that the clipboard is also purged when switching into offline mode instead of logging in

**Comment by eloquence** [comment]
Observing that the production log errors in case of missing keys are pretty verbose, including tracebacks and fingerprints, in case there's interest in reducing the verbosity prior to release. Example logs:
sync-errors

**Comment by eloquence** [comment]
Will step through some of https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests tomorrow to check for regressions.

**Comment by eloquence** [comment]
-  Environment type: Qubes staging
- Client version: 20200520 nightly
- Workstation version: 0.3.0rc1
- Server version: Qubes staging

- [x] Test with a large number of sources (300+ range) to ensure that that long metadata syncs show a continuous sync animation. 
- [x] Confirm that you can copy the contents of messages or replies to a VM tagged with sd-receive-app-clipboard

Regarding sync behavior with a populated server, I've observed the following:
- A sync of 314 sources generated using `qa_loader.py` takes approximately 20 seconds.
- The animation finishes just after we see the results of the sync in the client log.
- During the initial sync, I've noticed the "Retrieving new messages" status pop up a couple of times instead of only once. I'm ignoring that for now (I'm curious if it is related to #975?); ultimately we want that message and an animation to be displayed through the entire retrieval period.

**Comment by eloquence** [comment]
For regression testing I'll now take a stab at some of the scenarios in https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests , starting with >Scenario: Online mode

Note: I still don't have a supported printer; for future test runs it would be super useful to have 1:1 guidance on how to get an unsupported printer to work, if that's a reasonable proxy, so we don't all have to get Brother printers for basic regression testing (not that we've really made changes in this area, so not a huge priority for this time around).

**Comment by eloquence** [comment]
#### Login

- [x] when SecureDrop desktop icon is double-clicked, preflight updater is displayed
- [x] After preflight updater runs, when user clicks **Continue**, login dialog is displayed
- In login dialog:
  - [x] show/hide password functionality works
  - [x] incorrect password cannot log in
  - [x] 2FA token reuse cannot log in after password failure
  - [x] invalid 2FA token cannot log in
  - [x] valid credentials and 2FA can log in

#### Sources

- after valid login:
  - [x] the login dialog closes
  - [x] source data is downloaded and source list is populated
  - [x] user is prompted for GPG key access
  - [x] submissions and replies are decrypted
  - [x] the source list is displayed but no sources are selected by default
  - [x] the conversation view is not populated
- when a source is selected in source list:
  - [x] conversation view is populated with source conversation 
  - [x] a source message containing HTML is displayed as unformatted text
  - [x] source submissions have an active **Download** button
  - [x] source submission compressed file size is displayed accurately
- when the upper right 3-dot button is clicked:
  - [x] a menu is displayed with a **delete source account** option
  - when **delete source account** is selected:
    - [x] the source is deleted from the source list and the conversation view is blanked
    - [x] the source is deleted from the server and not restored on next sync
    - [x] source submissions and messages are removed from the client's data directory
- when a source is starred in source list, and the client is closed and reopened in Online mode:
  - [x] the source is still starred in the source list

#### Replies

- when a source is selected in the source list:
  - [x] the reply panel is available for use and there is no message asking the user to sign in
  - [x] a reply can be added to the conversations
  - [x] a reply containing HTML is displayed as unformatted text
  - :x: a reply with a single string of characters longer than 100 chars is displayed correctly (known issue, #815)
  - [x] a reply with a line longer than 100 chars is displayed correctly
  - [x] two replies added immediately after each other are ordered correctly
 
#### Submissions

##### Preview

- when **Download** is clicked on a submission:
  - [x] the submission is downloaded and decrypted
  - [x] the Download button is replaced with **Print** and **Export** options
  - [x] the submission filename is displayed.
- For a DOC submission:
   - [x] when the submission filename is clicked, a disposable VM (dispVM) is started.
   - [x] after the dispVM starts, the submission is displayed in LibreOffice
   - [x] when LibreOffice is closed, the dispVM shuts down
- For a PDF submission:
   - [x] when the submission filename is clicked, a dispVM is started.
   - [x] after the dispVM starts, the submission is displayed in evince
   - [x] when evince is closed, the dispVM shuts down
- For a JPEG submission:
   - [x] when the submission filename is clicked, a dispVM is started.
   - [x] after the dispVM starts, the submission is displayed in Image Viewer
   - [x] when image viewer is closed, the dispVM shuts down

**Comment by eloquence** [comment]
##### Export

- When **Export** is first clicked on a submission:
  - [x] the "Preparing to export..." message is displayed
  - [x] the `sd-devices` VM is started
  - [x] the user is prompted to insert an Export USB
  - [x] On clicking **Cancel**, the prompt closes and the file is not exported
- When **Export** is clicked on the submission again:
  - [x] the "Preparing to export..." message is displayed
  - [x] the user is prompted to insert an Export USB
  - When the user inserts an invalid Export USB, attaches it to the sd-devices VM and clicks **OK**:
    - [x] a message is displayed indicating that the Export USB is invalid and
    the user is prompted to insert a valid device
- When **Export** is clicked on the submission again:
  - [x] the "Preparing to export..." message is displayed
  - [x] the user is prompted to insert an Export USB
  - When the user inserts a valid Export USB, attaches it to the sd-devices VM, and clicks **OK**:
    - [x] the user is prompted for the Export USB's password
  - When the user enters an invalid Export USB password and clicks **Submit**:
    - [x] a failure message is displayed and the user is prompted to enter the password again
  - When the user enters an valid Export USB password and clicks **Submit**:
    - [x] the file is saved to the Export USB
- When the user detaches the Export USB and mounts it on another VM or computer:
  - [x] the decrypted submission is available in on the Export USB, in a directory `sd-export-<timestamp>/export_data`
##### Print

Skipped due to lack of compatible printer, but also no expected impact from this release

#### Closing the client

- When the user clicks the main window close button:
  - [x] the client exits.

**Comment by eloquence** [comment]
Focusing next on
> Scenario: Client and Journalist Interface both in use
because we've previously seen several issues in this area and there have been some changes to sync behavior.

**Comment by eloquence** [comment]
Environment type: Qubes staging
Client version: 20200522 nightly
Workstation version: 0.3.0rc1
Server version: Qubes staging 1.3.0

### Scenario: Client and Journalist Interface both in use

> **Prerequisites:**
> 
> - server is available and contains source test data
> - client data directory is empty

#### Login

- [ ] when SecureDrop desktop icon is double-clicked, preflight updater is displayed *(updater not re-tested)*
- [x] After preflight updater runs, when user clicks **Continue**, login dialog is displayed
- after valid login to client:
  - [x] the login dialog closes
  - [x] source data is downloaded and source list is populated
  - [ ] user is prompted for GPG key access *(previously granted)*
  - [x] submissions and replies are decrypted
  - [x] the source list is displayed but no sources are selected by default
  - [x] the conversation view is not populated
- when the JI address is visited in Tor Browser:
  - [x] JI login page is displayed
- after valid login to JI using same account as for client:
  - [x] sources page is displayed, containing the same sources as the client (order may differ)

#### Sources, replies, submissions

- when a source is starred in the client:
  - [x] the source is also starred in the JI after a page reload
- when a starred source is unstarred in the JI:
  - [x] the source is also unstarred in the client after next sync.
- when a reply is sent to a source via the client:
 - [x] the reply is visible in the JI and can be viewed by the source in the Source Interface
- when a reply is sent to a source via the JI:
  - [x] the reply is visible in the source conversation view after next sync

However, during this test, noticing a CPU spike in the late stage of the sync of ~350 sources, investigating a bit further.

**Comment by creviera** [comment]
> However, during this test, noticing a CPU spike and temporary client sluggishness in the late stage of the sync of ~350 sources, investigating a bit further.

There is a known issue and PR open that we can merge after this release (don't want it to be part of the release) that I think will address this issue, see https://github.com/freedomofpress/securedrop-client/pull/975 and https://github.com/freedomofpress/securedrop-client/issues/1095#issuecomment-634266993 for an explanation.

Other than that, it looks like tests are passing and we're ready to merge? No concerns on my end.

**Comment by kushaldas** [comment]
server: 1.3.0 prod vm
client: `0.1.6-dev-20200528-060128-buster`


**Fix for #1033 (merged in #1045)** 
- [x] Confirm that the baseline of filenames in the client is correctly aligned with Export/Print actions (i.e. [this minor rendering issue](https://user-images.githubusercontent.com/213636/78064524-bfbd9880-7346-11ea-93cc-ac23e05b3c85.png) should no longer occur)

**Fix for #1042 (merged in #1043)**
- [x] Confirm that when performing the first sync of a client against a server with multiple sources, sources at the top of the list should have their messages and replies populated first. You should be able to see the progress of the sync as it works down through the source list.

**Fix for #1053 (merged in #1057) and increased sync timeout (merged in #1055)**
- [x] Sync with a small number of sources to ensure that every 15 seconds you see an animation pulse. Test with a large number of sources (300+ range) to ensure that that long metadata syncs show a continuous sync animation.
- [x] Confirm that there are no other regressions during these syncs.

**Fix for #1030 (merged in #1058)**
- [x] Confirm that leading and trailing whitespace is trimmed from source messages and replies 

**Fix for #1052 (merged in #1063) and #1064 (merged in #1065)**
- [x] Confirm that you can select the contents of individual messages or replies with the mouse (left-click).
- [x] Confirm that you can use standard keyboard shortcuts (`Ctrl+C` and `Ctrl+V`) to copy and paste these messages within `sd-app`
- [x] Confirm that this can be used as a workaround for #815 by submitting a very long source string (e.g., `0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789`) and selecting it.
- [x] Confirm that right-clicking in the Conversation View has no effect
- :negative_squared_cross_mark: *When testing with https://github.com/freedomofpress/securedrop-workstation/pull/533* Confirm that you can copy the contents of messages or replies to a VM tagged with `sd-receive-app-clipboard` (I could not copy file or text to/from)

**Fix for #1060 (merged in #1069)**
- [x] Observe that the logs for downloaded messages, replies and files no contain empty strings, and that the folder names in the logs are correct
- [x] Observe that the logs do not include sensitive original filenames (e.g., an uploaded file `moscow.avi` should not appear in the logs under that name after the file is downloaded in the client)

**Fix for #140 (merged in #1059)**
- (Re-)start the client
- Before logging in, in `sd-gpg`, run `mv /home/user/.gnupg /home/user/.gnupg.save` to delete the submission key.
- Log in. 
- [x] Confirm that messages and replies are gray and italic, containing decryption errors.
- Wait and watch the client log, confirming that messages and replies are never being retried because of the download failures.
- Back in `sd-gpg`, run `rm -rf /home/user/.gnupg && cp -ax /home/user/.gnupg.save /home/user/.gnupg`.
- [x] Wait for the next sync; the failed downloads should not be retried and should not change their visual state, even though the key is now present.
- [x] Restart the client. All the failed downloads should be retried, and the conversation views should update to normal status.

**Fix for #1051 (merged in #1071)**
-  (Re-)start the client
- While the login screen is displayed, copy some string into the clipboard, e.g., "asdf" or your password
- [x] Observe that the string you copied can be successfully pasted multiple times
- Log into the client
- [x] Observe that the string you copied can no longer be pasted into the reply box
- [x] Verify that the clipboard is also purged when switching into offline mode instead of logging in

**Pull request merged**
