### PR TITLE
Remove unused API.get_current_user()

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description

This was superseded by `get_users()` in 74d0eb001e (which I missed while reviewing that PR!).

## Test Plan

* [ ] Visual review
* [ ] CI passes

## Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [x] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [x] No update to the AppArmor profile is required for these changes

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [x] No database schema changes are needed

[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-migrations

### CODE REVIEW

**Comment by cfm** [comment]
I hate to get in the way of deleting unused code, but bear with me:  I would argue that the SDK should provide a `get_current_user()` method as long as the API provides a `GET /api/v1/user` endpoint, whether or not any client using the SDK calls/consumes that method/endpoint.  Obviously, in this case the Client is the canonical user of both the SDK and the API, so the fact that the method is no longer used calls into question the usefulness of the endpoint.

@legoktm, is there an argument you can make explicit here for why this method/endpoint *should* not exist anymore, whether or not it *is* used?

**Comment by legoktm** [comment]
I think tying the SDK to the API like that is reasonable. I think the weird part is that we're okay making breaking changes to the SDK (as its embedded in the client, and e.g. removal of the `from_string` methods), but we'd be less okay making breaking changes to the server API , like in this case it would win us very little and risks breaking an unknown number of things.

And then keeping this method in the SDK is pretty minor and probably provides just a little bit of value in being an integration test for the API endpoint. But if we keep it I'd like to add a comment explicitly noting that it's unused.

**Comment by cfm** [comment]
I think that would be my preference, if you can stand it.  Next week I'd be happy to toss a note into the SDK's readme to the effect of "this SDK = that API, which is effectively frozen", by way of documenting this assumption.

**Comment by cfm** [comment]
Marking this blocked on #2221.

**Pull request closed without merging**
