### PR TITLE
Prevent content from re-appearing after "Files and Messages" deletion

### PR DESCRIPTION
**Pull request by creviera**
# Description

Fixes https://github.com/freedomofpress/securedrop-client/issues/1285

This is in draft mode to get feedback early while I work on adding an alembic migration test and confirm fix.

# Test Plan

https://github.com/freedomofpress/securedrop-client/issues/1285 is fixed

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [x] I have tested these changes in the appropriate Qubes environment
 - [ ] I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - [ ] These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - [ ] I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - [ ] I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - [x] I have written a migration and upgraded a test database based on `main` and confirmed that the migration applies cleanly
 - [ ] I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - [ ] I need help writing a database migration
 - [ ] No database schema changes are needed

### CODE REVIEW

**Comment by creviera** [comment]
This is still in draft mode until I add tests for the new code paths:
> securedrop_client/gui/widgets.py            2531      4    99%   3495, 3499-3500, 3542

Just pushing my changes since they're at a good stage for testing to see if the issue is fixed with the latest changes.

**Comment by eloquence** [comment]
Thanks for continuing to chip away at this thorny issue, @creviera! I'm still seeing the bug on this branch (I saw it immediately after deleting a conversation using "Files and Messages"), but I think we're much closer to resolving it. 

The behavior I'm seeing in the client and the logs is as follows:
- We get the notification from the server that the conversation has been deleted almost immediately (<5 seconds)
- The "deletion in progress" animation stops shortly after that.
- The conversation is displayed again in its pre-deleted state for a longer time (approx. ~10 seconds or more).
- Finally, the client catches up and puts in place the expected "Files and messages deleted" empty state.

Here's an unedited segment of logs from my testing. This is from deleting a conversation with just a single reply. The ^^^ insertions point to the log line exactly above, not the entire block.

```
2021-11-05 14:31:44,236 - securedrop_client.queue:110(add_job) DEBUG: Added <securedrop_client.api_jobs.sources.DeleteConversationJob object at 0x749a1c396048> to queue
2021-11-05 14:31:47,602 - securedrop_client.storage:116(get_remote_data) INFO: Fetched 12 remote sources.
2021-11-05 14:31:47,603 - securedrop_client.storage:117(get_remote_data) INFO: Fetched 4 remote submissions.
2021-11-05 14:31:47,604 - securedrop_client.storage:118(get_remote_data) INFO: Fetched 4 remote replies.
2021-11-05 14:31:47,607 - securedrop_client.storage:228(update_sources) DEBUG: Updated source f20c06ad-8d75-4a6c-9202-344097bc0812
2021-11-05 14:31:47,608 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 5a584da4-4644-4e7d-902f-120504cdb31f
2021-11-05 14:31:47,609 - securedrop_client.storage:228(update_sources) DEBUG: Updated source ed2746fb-0c00-4371-b1f0-e64689ec123d
2021-11-05 14:31:47,610 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 759ce62b-201a-4203-88ce-01087030480d
2021-11-05 14:31:47,610 - securedrop_client.logic:1021(on_delete_conversation_success) INFO: Conversation 8f52683a-f09e-4d06-a47b-4d655bc464ca successfully deleted at server
```

^^^ Note how we reached this point within just three seconds.


```
2021-11-05 14:31:47,611 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 0127a1d0-f168-46da-aa99-77b5f4bc949f
2021-11-05 14:31:47,612 - securedrop_client.storage:228(update_sources) DEBUG: Updated source e6ba210c-6a15-460b-8d03-576e34b2acce
2021-11-05 14:31:47,613 - securedrop_client.storage:228(update_sources) DEBUG: Updated source d7497a58-fa27-4d25-9d6c-632887b8bfb4
2021-11-05 14:31:47,615 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 3de5d053-0f48-4753-9742-c884b191998f
2021-11-05 14:31:47,615 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 6a3026be-4ba1-49f2-bbf7-fdda639fb94a
2021-11-05 14:31:47,616 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 25b26f57-6a64-4821-b139-61acaf0eb02c
2021-11-05 14:31:47,616 - securedrop_client.storage:228(update_sources) DEBUG: Updated source be76f2b7-6353-45ff-a248-99af25c8c7db
2021-11-05 14:31:47,617 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 8f52683a-f09e-4d06-a47b-4d655bc464ca
2021-11-05 14:31:47,619 - securedrop_client.storage:204(chronometer) INFO: update_sources duration: 0.0144s
2021-11-05 14:31:47,624 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated File c49e943d-c453-41ee-b33a-69e579f1d98e
2021-11-05 14:31:47,627 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated File a5f1038d-36dd-47de-aea6-06bcdf8802c3
2021-11-05 14:31:47,630 - securedrop_client.storage:204(chronometer) INFO: update_files duration: 0.0106s
2021-11-05 14:31:47,638 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated Message 15293e7f-6fee-43d7-b17e-7afddaa7a706
2021-11-05 14:31:47,644 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated Message 06100044-4b14-42f4-aa3c-9eea7cef0d78
2021-11-05 14:31:47,645 - securedrop_client.storage:204(chronometer) INFO: update_messages duration: 0.0140s
2021-11-05 14:31:47,650 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply cec7cca4-c756-4ead-804b-17a5337b90f5
2021-11-05 14:31:47,653 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply 51413e80-65e5-4231-a1ab-e3b97eb3657c
2021-11-05 14:31:47,658 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply 851b048d-2a68-4c31-8cb5-1684dc9408e5
2021-11-05 14:31:47,660 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply 1c0f35d0-c140-4c9d-99d0-4b2d6120bfc7
2021-11-05 14:31:47,662 - securedrop_client.storage:204(chronometer) INFO: update_replies duration: 0.0170s
2021-11-05 14:31:51,256 - securedrop_client.gui.widgets:665(on_source_changed) DEBUG: Set conversation to the selected source with uuid: 8f52683a-f09e-4d06-a47b-4d655bc464ca
```

^^^ I've not correlated exactly, but it looks like this may be the point when we're showing the pre-deleted state again.

```
2021-11-05 14:31:51,262 - securedrop_client.queue:268(resume_queues) DEBUG: Resuming main queue
2021-11-05 14:31:51,263 - securedrop_client.queue:271(resume_queues) DEBUG: Resuming download queue
2021-11-05 14:32:03,561 - securedrop_client.storage:116(get_remote_data) INFO: Fetched 12 remote sources.
2021-11-05 14:32:03,563 - securedrop_client.storage:117(get_remote_data) INFO: Fetched 4 remote submissions.
2021-11-05 14:32:03,563 - securedrop_client.storage:118(get_remote_data) INFO: Fetched 3 remote replies.
2021-11-05 14:32:03,567 - securedrop_client.storage:228(update_sources) DEBUG: Updated source f20c06ad-8d75-4a6c-9202-344097bc0812
2021-11-05 14:32:03,567 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 5a584da4-4644-4e7d-902f-120504cdb31f
2021-11-05 14:32:03,568 - securedrop_client.storage:228(update_sources) DEBUG: Updated source ed2746fb-0c00-4371-b1f0-e64689ec123d
2021-11-05 14:32:03,569 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 759ce62b-201a-4203-88ce-01087030480d
2021-11-05 14:32:03,569 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 0127a1d0-f168-46da-aa99-77b5f4bc949f
2021-11-05 14:32:03,570 - securedrop_client.storage:228(update_sources) DEBUG: Updated source e6ba210c-6a15-460b-8d03-576e34b2acce
2021-11-05 14:32:03,571 - securedrop_client.storage:228(update_sources) DEBUG: Updated source d7497a58-fa27-4d25-9d6c-632887b8bfb4
2021-11-05 14:32:03,572 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 3de5d053-0f48-4753-9742-c884b191998f
2021-11-05 14:32:03,573 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 6a3026be-4ba1-49f2-bbf7-fdda639fb94a
2021-11-05 14:32:03,574 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 25b26f57-6a64-4821-b139-61acaf0eb02c
2021-11-05 14:32:03,575 - securedrop_client.storage:228(update_sources) DEBUG: Updated source be76f2b7-6353-45ff-a248-99af25c8c7db
2021-11-05 14:32:03,575 - securedrop_client.storage:228(update_sources) DEBUG: Updated source 8f52683a-f09e-4d06-a47b-4d655bc464ca
2021-11-05 14:32:03,578 - securedrop_client.storage:204(chronometer) INFO: update_sources duration: 0.0139s
2021-11-05 14:32:03,583 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated File c49e943d-c453-41ee-b33a-69e579f1d98e
2021-11-05 14:32:03,586 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated File a5f1038d-36dd-47de-aea6-06bcdf8802c3
2021-11-05 14:32:03,586 - securedrop_client.storage:204(chronometer) INFO: update_files duration: 0.0084s
2021-11-05 14:32:03,593 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated Message 15293e7f-6fee-43d7-b17e-7afddaa7a706
2021-11-05 14:32:03,597 - securedrop_client.storage:307(__update_submissions) DEBUG: Updated Message 06100044-4b14-42f4-aa3c-9eea7cef0d78
2021-11-05 14:32:03,598 - securedrop_client.storage:204(chronometer) INFO: update_messages duration: 0.0114s
2021-11-05 14:32:03,608 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply cec7cca4-c756-4ead-804b-17a5337b90f5
2021-11-05 14:32:03,611 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply 51413e80-65e5-4231-a1ab-e3b97eb3657c
2021-11-05 14:32:03,613 - securedrop_client.storage:454(update_replies) DEBUG: Updated reply 851b048d-2a68-4c31-8cb5-1684dc9408e5
2021-11-05 14:32:03,614 - root:738(delete_single_submission_or_reply_on_disk) INFO: Object /home/user/.securedrop_client/data/spectral_microsurgery/3-spectral_microsurgery-reply.txt already deleted, skipping
```

^^^ This is a bit surprising and I've seen it repeatedly, why is it trying to delete the file again?

```
2021-11-05 14:32:03,616 - securedrop_client.storage:499(update_replies) DEBUG: Deleted reply 1c0f35d0-c140-4c9d-99d0-4b2d6120bfc7
2021-11-05 14:32:03,697 - securedrop_client.storage:204(chronometer) INFO: update_replies duration: 0.0984s
2021-11-05 14:32:06,703 - securedrop_client.gui.widgets:3592(update_conversation) DEBUG: Deleting item: 1c0f35d0-c140-4c9d-99d0-4b2d6120bfc7
2021-11-05 14:32:06,707 - securedrop_client.gui.widgets:665(on_source_changed) DEBUG: Set conversation to the selected source with uuid: 8f52683a-f09e-4d06-a47b-4d655bc464ca
```

^^^ This seems to roughly correlate with when it finally switches to the deleted view.

**Comment by eloquence** [comment]
Per your request I took a quick spin - and I was no longer able to reproduce the original bug! :tada: 

I'm observing one regression: If a new source message or file comes in while the source is selected, the conversation view is no longer updated (I have to de-select and re-select it to see the new message or file; the preview snippet is updated immediately).

**Comment by eloquence** [comment]
Taking this for another spin now...

**Comment by eloquence** [comment]
I can confirm that I am no longer able to reproduce #1285, nor do I see any regressions. :tada:  In addition, "files and messages" deletion is now super-fast, which is lovely - it'll be great to update the "entire source" deletion implementation after 0.5.0 to get the same speed benefit.

**Comment by creviera** [comment]
just had to do a little rebasing to remove an unused import (`sys`) i don't remember making. other than that everything is the same since https://github.com/freedomofpress/securedrop-client/pull/1311#issuecomment-976104580 and so this is ready for review

**Comment by conorsch** [comment]
Tested pretty extensively. In the process, added to the wiki [some docs on injecting latency](https://github.com/freedomofpress/securedrop-client/wiki/Developer-Tips-&-Tricks#faking-a-slow-network-in-client-dev), to make some of the rendering woes (like #1285) significantly easier to reproduce. Using that a baseline, was able to verify that the issue is very much resolved for me.

### Before
client-repo-1285-in-pr-3

### After
client-1311-cannot-repro-1

The only remaining issue I see is that the latest iteration caused a test to fail. But the test should be updated, not the app code! The app code is behaving precisely how we want it to. Grooming the tests is a very small change yet to be added here, on top of the existing changeset. @creviera Let's test one more time early next week, and if CI is passing, we're good to go on 0.5.0 QA!

**Comment by creviera** [comment]
last change here removes the unused variable in `test_widgets.py`

I'm working on a formal QA test plan for `0.5.0`, but for this PR, let's just make sure #1285 is fixed without any regressions by:
- [ ] #1285 is fixed
- [ ] no detectable regressions (if you see something strange, confirm that it doesn't happen on `main` to help you decide whether or not to open a new issue)
   - [ ] you can still see failed replies, just like you can on `main`, after deleting a conversation
   - [ ] preview snippets show animation at the beginning and end of a deletion operation
   - [ ] preview snippet shows "All messages and files deleted" indicator after a deletion operation
   - [ ] preview snippet shows the last message of a conversation

**Comment by conorsch** [comment]
Performed another round of testing, with the latest changes. Looks great! I've one quibble with the test plan, namely:

> you can still see failed replies, just like you can on main, after deleting a conversation

That's not true for me, neither on this feature branch nor on main. In order to test, I created a failed reply like so:

1. Pause dev container
2. Send reply (will get stuck in "pending" state because server container server responds)
3. Exit client
4. Restart client (must use same home dir from previous run, via SDC_HOME)
5. Observe reply is now marked as failed

Using that workflow, failed replies are removed on both main and this feature branch.

### Behavior on 1311 (looks good)
sdc-1311-failed-msg-disappears-2

### Behavior on main
Note that because #1285 is not resolved on main, there are visual artifacts—that's expected! But failed replies are still removed. 
sdc-1311-failed-msg-disappears-2

That's the sole nit I have from most recent testing. As long as we have a solid test plan for QA, I'm comfortable proceeding with release. Will approve and leave merge to you, @creviera!

**Review by conorsch — APPROVED** [review]
Approving! @creviera see notes on test plan in my final comment; I suggest we address that in the QA for the 0.5.0 nightly packages, to be built tonight—no further changes requested on this PR.

**Comment by creviera** [comment]
@conorsch I think toxiproxy might be getting in the way of testing failed replies properly -- killing the client when the reply is pending will result in the reply being failed locally but if the reply is still being sent via toxiproxy then it will succeed on the server and then the failed reply will get promoted to a successful reply and be deleted. Here's what I see on both `main` and this PR branch when I make **sure** that the reply does not actually get sent to the server in the background (you can copy me by applying this diff https://gist.github.com/creviera/5ba70d50c12b6a6df6f98ed40ad09645): Peek 2021-11-29 19-11

I didn't get to making the QA test plan today but will finalize something tomorrow, which I will make sure has all the test steps to be more thorough.

**Comment by conorsch** [comment]
@creviera Thanks for explaining. Using your patch, I see the behavior you describe: failed replies persist in the chat window even after files & submissions are deleted. Better yet, when I test with both your patch and toxiproxy, I see a long (~5s) wait during the deletion operation, and the failed reply is still visible afterward. That now matches the test plan. I should have inspected the db contents to verify that my failed messages were staying failed! No concerns from me, we're good to proceed.

**Pull request merged**
