### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rocodes**
Add note on QT_QPA_PLATFORM variable for developers using Wayland

### CODE REVIEW

**Review by creviera — APPROVED** [review]
Tested this and it works for me. I also checked the docs here https://wiki.debian.org/Wayland under `Qt (supported since 5)` and this is the recommended environment variable to set.

**Comment by zenmonkeykstop** [comment]
Would it make sense for the script to just test for Wayland and set said env var appropriately?

**Comment by gonzalo-bulnes** [comment]
@rocodes I'm not merging this because my understanding is that #1653 would indeed replace it. (?)

**Comment by legoktm** [comment]
Closing now that #1653 has landed.

**Pull request closed without merging**
