### PR TITLE
chore: update to Jinja2 3.1.3 for Safety 64227

### PR DESCRIPTION
**Pull request by cfm**
## Status

Ready for review
- `verify-builder-sync` is blocked on freedomofpress/securedrop-builder#492.

## Description

Addresses Safety 64227, pinned to v3.1.3 because that's what's diff-reviewed for production in freedomofpress/securedrop#7107.

### CODE REVIEW

**Comment by rocodes** [comment]
@cfm I just restarted CI after merging https://github.com/freedomofpress/securedrop-builder/pull/492, but I would hope/expect it will fail without an update to`build-requirements.txt`. Mind throwing that in as well?

**Comment by cfm** [comment]
Oops; thanks, @rocodes.  I'd thought I was missing a loop-closing step somewhere.  Amended in 6d70de5974288407e50ce8aa91947c433d56c4cc.

**Comment by cfm** [comment]
Rebased to resolve a conflict in `client/poetry.lock` due to python-poetry/poetry#496, which will be worth keeping in mind.

**Review by legoktm — APPROVED** [review]
Let's get this landed then to avoid future conflicts :)

**Pull request merged**
