### PR TITLE
Add ReplyDownloadJob

### LINKED ISSUE #408: Create ReplyDownloadJob
## Description

Like #389, replace ReplySync with a ReplyDownloadJob

### PR DESCRIPTION
**Pull request by creviera**
# Description

Resolves #408

* Reply sync (download+decrypt) now occurs whenever there is a metadata sync with the server instead of every 5 seconds checking if there are new replies.
* We now use the queue to download and decrypt replies in a job called ReplyDownloadJob
* message_sync.py has been deleted and references to reply_sync and reply_thread removed
* User-facing behavior should remain the same with a few modifications to log messages

# Test Plan

1. Write a reply in the reply box and hit "Send"
2. Click between sources to check that it persists
3. Refresh, see it persist

### CODE REVIEW

**Comment by creviera** [comment]
Wait to merge this until https://github.com/freedomofpress/securedrop-client/pull/409 is merged

**Comment by kushaldas** [comment]
@creviera this one needs a rebase.

**Comment by redshiftzero** [comment]
This one will also close #122

**Comment by creviera** [comment]
This is ready for final review. https://github.com/freedomofpress/securedrop-client/issues/432 is a known issue that will be fixed outside this PR.

**Comment by creviera** [comment]
rebased ^

**Pull request merged**
