### PR TITLE
Fix outdated comment in generated requirements file

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
# Description

- Fixes outdated `requirements.txt` file. That failure was not picked up by CI.
- Adds a job to ensure future similar failures are detected in CI, because they're relevant to testing. (If we were to test using different Python dependencies than we use in production, that would be less than ideal and potentially problematic.)
- Ensures that the output of both requirement files checks (packaging and testing) is useful when failures happen.

# Test Plan

- [x] Confirm that the `requirements.txt` file hasn't changed significantly
- [x] Confirm that the step that checks the _packaging_ requirements hasn't changed significantly (hint: `git diff --help`)
- [x] Confirm that CI is green :green_apple: 

I have confirmed, so that you don't have to, that:

- If the packaging requirements are updated and the production requirements are not, the **build-bullseye** job fails, and outputs useful information. ([example](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/2563/workflows/e4dea347-f954-492c-8c52-cb337db9d070/jobs/10092?invite=true#step-104-6))
- If the testing requirements are updated and the production requirements are not, the **check-testing-requirements-bullseye** job fails, and outputs useful information. ([example](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/2564/workflows/f9d540bb-f6ab-42e3-a809-34e4485bf544/jobs/10107?invite=true#step-103-2352)

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
@legoktm Is it possible that https://github.com/freedomofpress/securedrop-debian-packaging/pull/373 being merged caused CI to fail over here?

I added debugging output to the job and this is what's being picked up: [source](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/2552/workflows/d8c3f569-be2f-4e65-8dc8-b29be0e7595d/jobs/10000)

```diff
diff --git a/requirements/build-requirements.txt b/requirements/build-requiremen
ts.txt
index 457607a..cbb6952 100644
--- a/requirements/build-requirements.txt
+++ b/requirements/build-requirements.txt
@@ -4,12 +4,12 @@ certifi==2021.5.30 --hash=sha256:2dee87f82eab7a047280038bacb5b
dbc4ee308ae39522cc
 charset-normalizer==2.0.4 --hash=sha256:cd9a4492eef4e5276c07f9c0dc1338e7be3e95f
2a536bf2c5b620b1f27d03d74
 idna==3.2 --hash=sha256:691d9fc304505c65ea9ceb8eb7385d63988e344c065cacbbd2156ff
9bdfcf0c1
 mako==1.0.7 --hash=sha256:99d041a616a3655725dffe459916627b75640a7d045ed33f51ce1
58a168ca3ef
-markupsafe==2.0.1 --hash=sha256:7b12b29ae39060c29ed0d8cb1052fa1672832b5096f859f
d35e896ca3b04ddd3 --hash=sha256:9a055a175f351a559937fb80ebb2885d005283577a016c01
39817e261fb759eb
+markupsafe==2.0.1 --hash=sha256:bb3e541812095075336bcd935bb58941aedc0a7cba3c73d
301dfdfd4d66a4eec --hash=sha256:7b12b29ae39060c29ed0d8cb1052fa1672832b5096f859fd
35e896ca3b04ddd3 --hash=sha256:9a055a175f351a559937fb80ebb2885d005283577a016c013
9817e261fb759eb
 pathlib2==2.3.2 --hash=sha256:90173e12465846173da76c62892b238c14a2a0e17aae58093
3041004fc01b713
 python-dateutil==2.7.5 --hash=sha256:2961735b604e5165d923a4e39b9bcbde6a4c363f25
```

**Comment by gonzalo-bulnes** [comment]
The new wheel hash will be introduced by https://github.com/freedomofpress/securedrop-client/pull/1554 unless I'm wrong.

**Comment by gonzalo-bulnes** [comment]
**For future reference**: the `main` nightlies started failing after https://github.com/freedomofpress/securedrop-debian-packaging/pull/373 was merged. (This was unexpected to me, but @eaon and I concluded that is was probably to be expected.)

Merging #1554 fixed the `main` build. (As was very likely @legoktm's intention.)

Independently of that, running `make requirements` locally does yield the comment update contained in this branch. I don't yet understand why this difference doesn't cause the CI pipeline to fail, since we [ostensibly check for it](https://github.com/freedomofpress/securedrop-client/blob/fix-outdated-comment-in-requirements-file/.circleci/config.yml#L126).

**Review by legoktm — APPROVED** [review]
LGTM, though I think we need to figure out how to keep less things copied around everywhere and then need less checks about things being in sync...

**Comment by legoktm** [comment]
@eloquence: could you add `check-testing-requirements-bullseye` as a required job please?

**Comment by eloquence** [comment]
Done. As before, open SecureDrop Client PRs will now need to be rebased to pass CI.

**Pull request merged**
