### PR TITLE
securedrop-client 0.0.5

### PR DESCRIPTION
**Pull request by redshiftzero**
for building new packages that are using the latest SDK

### CODE REVIEW

**Comment by kushaldas** [comment]
@redshiftzero I guess latest means `securedrop-sdk==0.0.3` ?

**Comment by redshiftzero** [comment]
ah nope we made a 0.0.4 release @kushaldas

**Comment by kushaldas** [comment]
@redshiftzero then this commit should also update the `requirements.txt` and also `Pipfile.lock`.

**Comment by redshiftzero** [comment]
(Pipfile.lock was updated in #143)

**Comment by redshiftzero** [comment]
recapping some discussion earlier in gitter: we should generate requirements.txt (used only for build) at the time of building the wheel packages, and this step should be automated

**Pull request merged**
