### PR TITLE
Version 0.0.8

### PR DESCRIPTION
**Pull request by creviera**
Update to version 0.0.8

This has the pipenv -> pip-tools change, which will unblock https://github.com/freedomofpress/securedrop-debian-packaging/pull/44 and https://github.com/freedomofpress/securedrop-debian-packaging/issues/48

### CODE REVIEW

**Comment by redshiftzero** [comment]
the CI failure here looks like https://github.com/PyCQA/bandit/issues/488

**Comment by redshiftzero** [comment]
ah yeah, new bandit release (1.6.1) with a fix for the above bug that doesn't appear to be working here...

**Comment by redshiftzero** [comment]
@creviera want to append a commit pinning to the version that doesn't suffer from this bug, e.g.:

```diff
diff --git a/Makefile b/Makefile
index 6635db9..cf0ab18 100644
--- a/Makefile
+++ b/Makefile
@@ -57,7 +57,7 @@ safety: ## Runs `safety check` to check python dependencies for vulnerabilities
 .PHONY: bandit
 bandit: ## Run bandit with medium level excluding test-related folders
        pip install --upgrade pip && \
-        pip install --upgrade bandit!=1.6.0 && \
+        pip install --upgrade bandit==1.5.1 && \
        bandit -ll --recursive . --exclude tests,.venv

 .PHONY: check
```

then we can file an issue for unpinning as followup

**Comment by creviera** [comment]
I tested building the debian package in qubes and was able to log into the client and see decrypted messages.

**Comment by redshiftzero** [comment]
Looks good - can you push a 0.0.8 tag on f526a122bbb33f26446423209511b6566d3d5945 (flagging the commit here since the tag should be on this specific commit)?

**Comment by redshiftzero** [comment]
confirming successful build on these changes: https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/25

**Pull request merged**
