### PR TITLE
Add branding image to left pane and polish styling

### LINKED ISSUE #518: [client styling] Apply branding bar background image
As seen in many Zeplin screens like [this one](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5cfe9244f033df15f09e72ec), we want a branding bar to be displayed on the left-hand side, showing a background image with the SecureDrop logo. The scope of this issue is only to apply the background image to the branding bar as seen in the specification. The addition of the "All sources" tab is out of scope for this issue.

### PR DESCRIPTION
**Pull request by creviera**
Resolves #518

# Description

I could not find an issue for polishing the left pane and applying the "branding" image background. But here you'll find:

* User icon character spacing correct width of 0.58
* User profile widget formatted with the updated margins and padding
* User dropdown menu button closer to the edge with updated margins and padding
* branding background image that spans across the left pane and resizes correctly (little trick to stretch blue widget from the top for larger screen sizes)

### CODE REVIEW

**Comment by creviera** [comment]
Here's what it looks like now:

left-pane

**Comment by creviera** [comment]
Resolves https://github.com/freedomofpress/securedrop-client/issues/518

**Comment by creviera** [comment]
For review, compare with [zeplin brading bar](https://app.zeplin.io/project/5c807ea562f734bd2756b243/styleguide/components?seid=5ca3e427ea78dc066b00825b) which includes the user profile widget (user icon with the two letters, aka user badge, user name, and dropdown menu)

**Comment by ninavizz** [comment]
SVG art for this has been updated in the [Content Inventory](https://github.com/freedomofpress/securedrop-ux/issues/17). :)

**Comment by creviera** [comment]
Note: The svg aspect ratio does not match the left pane dimensions when the client is maximum size, so I added a blue widget at the top of the left pane that can respond to window resizing by stretching.

**Pull request merged**
