### PR TITLE
mechanizes continuous-localization workflow

### LINKED ISSUE #1266: script continuous-localization workflow between GitHub repository and Weblate component
After #1264, implement a workflow to run on commits to Weblate's tracking branch (see below):

0. [x] GitHub Actions workflow: nightly run
1. [x] `pybabel extract` source strings → `.pot`
    - [x] including translator comments (per #1265)
    - [x] commit
2. [x] `msgmerge` `.pot` → `.po`
    - [x] commit
3. [x] Compile `.po` → `.mo`
    - [x] When is this (automatically) committed?  →  It isn't; it's used in packaging and at development runtime.
3. [x] Store or [retrieve](https://docs.weblate.org/en/latest/api.html#get--api-components-(string-project)-(string-component)-translations-) [list of supported (100% translated) locales](https://github.com/freedomofpress/securedrop/blob/826c178f3d9e59b829c42f6afe619ee23fae45bd/securedrop/i18n_tool.py#L30-L61)
    - For SecureDrop Server, this lives in [`securedrop-docs/docs/includes/l10n.txt`](https://github.com/freedomofpress/securedrop-docs/blob/main/docs/includes/l10n.txt). 
    - This designation, and the process for granting/revoking it, might be worth formally reconsidering—though the stakes are lower on the Journalist Interface (and client) than on the Source Interface.
    - [x] commit
4. Give credit to contributing translators → #1280

Once tested manually, these operations can be scripted (either separately or as Makefile targets) initially for manual invocation, but [continuous localization](https://docs.weblate.org/en/latest/admin/continuous.html) will require running them as part of CI.  (A goal of this effort, in any case, is to avoid replicating the complexity of `securedrop`'s `i18n_tool.py`.)  In the latter case, Weblate's tracking branch will be:

1. `i18n-testing` for the purposes of this ticket; and then
2. `main` upon `i18n-testing`'s approval for merge into `main`.

If "naïve" continuous localization (committed directly to the tracking branch) turns out to be a hassle (e.g., by cluttering Git history with noisy Weblate-related commits that maintainers find annoying), we can make the workflow [asymmetric](https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate), in which:

1. source strings are made available for continuous translation (`main` → Weblate); but
2. translations are pushed only to ~an `i18n` branch~ a fork, from which a PR is opened for review (Weblate → fork → PR → `main`).

_Originally posted by @cfm in https://github.com/freedomofpress/securedrop-client/issues/239#issuecomment-867852782_

## [Process diagrams](https://gist.github.com/cfm/416b18a700545e63188a4daef21d599f) ([Mermaid](https://mermaid-js.github.io/mermaid-live-editor/edit#))

| Filename | Version | Description |
| --- | --- | --- |
| `weblate-r0.mmd` | 0 | Weblate canonical workflow—adapted from [their Graphviz](https://github.com/WeblateOrg/weblate/blob/main/docs/admin/continuous.rst) |
| `securedrop-client-r1.mmd` | 1 | `main` → Weblate → fork → PR → `main` |

## Subtasks

1. [x] r1 tested manually
2. [x] r1 scripted in Makefile targets

### PR DESCRIPTION
**Pull request by cfm**
# Description

Closes #1266 by providing the following mechanisms for integrating with Weblate's [workflow for continuous localization](https://docs.weblate.org/en/weblate-4.6/admin/continuous.html#), contrasted below with their equivalents in `securedrop`'s [phased workflow](https://docs.securedrop.org/en/stable/development/i18n.html).  An explicit goal of #1266 is to avoid replicating the complexity of `securedrop`'s `i18n_tool.py`.

| Step | Implemented here as | Implemented in `securedrop` as |
| --- | --- | --- |
| Update strings to be translated | Nightly CI workflow[1] for `make update-translation-catalogs` | `make translate` → `i18n_tool.py translate-messages` |
| Merge ~`develop`~`main` with Weblate fork | Weblate pulls automatically | Localization Manager [merges manually](https://docs.securedrop.org/en/stable/development/i18n.html#merge-develop-into-the-weblate-fork) |
| Merge translations back to ~`develop`~`main` | Weblate opens[3] pull request automatically | Localization Manager [merges manually](https://docs.securedrop.org/en/stable/development/i18n.html#merge-translations-back-to-develop) |
| —Compile translations | Runtime[2] `make compile-translation-catalogs` | Manual `i18n_tool.py translate-messages --compile` |

**Notes:**

1. This is implemented as a GitHub Actions workflow for ease of pushing changes back into this repository.  If this is undesirable tool-sprawl, it will be trivial to port this workflow into CircleCI à la https://github.com/freedomofpress/infrastructure/issues/1904#issuecomment-503796888, at the cost of being somewhat less easy to trigger manually in addition to on a schedule.
    * **NB.**  We should carefully consider the security implications of this, since `securedrop-client` unlike `securedrop-debian-packaging` runs CI on pull requests including from forks.
2. In development only, pending #1283.
3. Think of this as an upsert:  Weblate will open a new pull request `weblate-fpf/securedrop-client@weblate-securedrop-securedrop-client` → `freedomofpress/securedrop-client@main` only if it isn't already open.

### Weblate's generic continuous-localization workflow

Adapted from their [documentation](https://docs.weblate.org/en/weblate-4.6/admin/continuous.html#) and [Graphivz](https://github.com/WeblateOrg/weblate/blob/main/docs/admin/continuous.rst):

[](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcblxuZGV2ZWxvcGVyc1tEZXZlbG9wZXJzXVxuV2VibGF0ZSgoV2VibGF0ZSkpXG50cmFuc2xhdG9yc1t0cmFuc2xhdG9yc11cblxuZGV2ZWxvcGVycyAtLTEuIFB1c2gtLT4gbWFpblxubWFpbiAtLlwiMi4gW0RhaWx5XSBVcGRhdGluZzxicj4oZXh0cmFjdGluZyttZXJnaW5nKTxicj50cmFuc2xhdGlvbnNcIi4tPiBtYWluXG5tYWluIC0tXCIzLiBQdWxsIChvciB3ZWIgaG9vaylcIi0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tNC4gTm90aWZpY2F0aW9uLS0-IHRyYW5zbGF0b3JzXG50cmFuc2xhdG9ycyAtLTUuIFRyYW5zbGF0ZS0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tNi4gUHVzaC0tPiBXZWJsYXRlTWFpblxuV2VibGF0ZU1haW4gLS03LiBQUi0tPiBtYWluXG5cbnN1YmdyYXBoIEdpdEh1Ylxuc3ViZ3JhcGggZnJlZWRvbW9mcHJlc3Mvc2VjdXJlZHJvcC1jbGllbnRcbm1haW5bXCJtYWluPGJyPihpMThuLXRlc3RpbmcpXCJdXG5lbmRcblxuc3ViZ3JhcGggV2VibGF0ZSBmb3JrXG5XZWJsYXRlTWFpblttYWluXVxuZW5kXG5cbmVuZCIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOnRydWUsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ)

### Workflow implemented in this pull request

[](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcblxuZGV2ZWxvcGVyc1tEZXZlbG9wZXJzXVxuV2VibGF0ZSgoV2VibGF0ZSkpXG50cmFuc2xhdG9yc1t0cmFuc2xhdG9yc11cblxuZGV2ZWxvcGVycyAtLTEuIFB1c2gtLT4gbWFpblxubWFpbiAtLlwiMi4gW0RhaWx5XSBVcGRhdGluZzxicj4oZXh0cmFjdGluZyttZXJnaW5nKTxicj50cmFuc2xhdGlvbiBjYXRhbG9nc1wiLi0-IG1haW5cbm1haW4gLS1cIjMuIFB1bGwgKHRyaWdnZXJlZCBieSB3ZWIgaG9vaylcIi0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tNC4gTm90aWZpY2F0aW9uLS0-IHRyYW5zbGF0b3JzXG50cmFuc2xhdG9ycyAtLTUuIFRyYW5zbGF0ZS0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tXCI2LiBQdXNoPGJyPihpbmNsdWRpbmcgdXBzdHJlYW08YnJjb21taXRzIGZyb20gc3RlcCAzKVwiLS0-IFdlYmxhdGVNYWluXG5XZWJsYXRlTWFpbiAtLTcuIFBSIC0tPiBtYWluXG5cbnN1YmdyYXBoIEdpdEh1Ylxuc3ViZ3JhcGggZnJlZWRvbW9mcHJlc3Mvc2VjdXJlZHJvcC1jbGllbnRcbm1haW5bXCJtYWluXCJdXG5lbmRcblxuc3ViZ3JhcGggd2VibGF0ZS1mcGYvc2VjdXJlZHJvcC1jbGllbnRcbldlYmxhdGVNYWluW3dlYmxhdGUtc2VjdXJlZHJvcC1zZWN1cmVkcm9wLWNsaWVudF1cbmVuZFxuXG5lbmRcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

# Test Plan

I can also arrange (or record) a demo of the end-to-end workflow.

1. [ ] On `1266-continuous-l10n` (and inside the virtual environment):

        $ make update-translation-catalogs
        $ git push -f origin 1266-continuous-l10n:i18n-testing

    - This simulates the `l10n` workflow that will run every night on `main`.
2. [ ] <https://weblate.securedrop.org/projects/securedrop/securedrop-client/#repository>: Go to **Maintenance** and select **Reset**.
3. [ ] <https://weblate.securedrop.org/projects/securedrop/securedrop-client/>: **Start a New Translation** for `es`.
4. [ ] Observe 2 new commits (after `1266-continuous-l10n`) in [`weblate-fpf/securedrop-client@weblate-securedrop-securedrop-client`](https://github.com/weblate-fpf/securedrop-client/commits/weblate-securedrop-securedrop-client).
5. [ ] <https://weblate.securedrop.org/translate/securedrop/securedrop-client/es/?q=>: Search for the string `username` and suggest `Nombre de Usuario`.
    * **WARNING.**  Be careful to enter only correct translations when testing at the production weblate.securedrop.org.  Weblate will happily sync translations of identical source strings between `securedrop` and `securedrop-client`, which can pollute the translation (or at least the Git history) of the former.
6. [ ] <https://weblate.securedrop.org/projects/securedrop/securedrop-client/#repository>:  Select **Commit**.
7. [ ] Observe 3 commits (after `1266-continuous-l10n`) in [`weblate-fpf/securedrop-client@weblate-securedrop-securedrop-client`](https://github.com/weblate-fpf/securedrop-client/commits/weblate-securedrop-securedrop-client).
8. [ ] In a `securedrop-client` development environment (i.e., with the virtual environment activated):

        $ git remote add weblate-fpf https://github.com/weblate-fpf/securedrop-client
        $ git fetch weblate-fpf
        $ git checkout weblate-fpf/weblate-securedrop-securedrop-client
        $ LANG=es_ES ./run.sh

9. [ ] Observe that the **Username** label on the login screen has been translated.

# Checklist

If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check as applicable:

 - [x] I have tested these changes in the appropriate Qubes environment
 - I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
 - These changes should not need testing in Qubes

If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as applicable:

 - I have updated the [AppArmor profile](https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client)
 - [x] No update to the AppArmor profile is required for these changes
 - I don't know and would appreciate guidance

If these changes modify the database schema, you should include a database migration. Please check as applicable:

 - I have written a migration and upgraded a test database based on `main` and confirmed that the migration applies cleanly
 - I have written a migration but have not upgraded a test database based on `main` and would like the reviewer to do so
 - I need help writing a database migration
 - [x] No database schema changes are needed

## Pre-merge steps

1. [x] Remove "restricted" status from `securedrop-client` Weblate component
2. [x] Remove [`FIXME`](https://github.com/freedomofpress/securedrop-client/compare/main...1266-continuous-l10n#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R157) in `supported-languages` Make target

## Post-merge steps

1. [ ] <https://weblate.securedrop.org/settings/securedrop/securedrop-client/#vcs>: Change **Repository Branch** to `main`
2. [ ] Monitor daily `l10n` GitHub Actions workflow for successful `update-translation-catalogs`

## Known issues

1. CircleCI will run the `securedrop_client_ci` workflow even for each new head of Weblate's fork, because it sees the source branch `weblate-securedrop-securedrop-client` through the pull request opened by Weblate.  ([This looks to CircleCI like `pull/1281`](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/); there's no other information about the pull request available to use in filtering logic.)

### CODE REVIEW

**Comment by cfm** [comment]
Re: failing `test-buster`:  These are linting failures caused by `gettext.translation().install()`.  `flake8` [can be placated with `--builtins`](https://stackoverflow.com/questions/37840142/how-to-avoid-flake8s-f821-undefined-name-when-has-been-installed-by-get); mypy is [trickier](https://github.com/python/mypy/issues/8727).  I've returned this pull request to draft status while I work on a fix.

**Comment by creviera** [comment]
following the test plan i'm seeing a 404 here: https://weblate.securedrop.org/projects/securedrop/securedrop-client/#repository

**Review by creviera — CHANGES_REQUESTED** [review]
I think you need to allow members of the sd-maintainers group perms for https://weblate.securedrop.org/projects/securedrop/securedrop-client/#repository

**Comment by cfm** [comment]
https://github.com/freedomofpress/securedrop-client/pull/1282#pullrequestreview-751813836:

> I think you need to allow members of the sd-maintainers group perms for https://weblate.securedrop.org/projects/securedrop/securedrop-client/#repository

Ah; I'd assumed that you would have more access than I.  :-)  I've unmarked the "SecureDrop Client" component as "restricted", which should let you access it just like the other Weblate components.

**Review by creviera — DISMISSED** [review]

**Review by creviera — COMMENTED** [review]
@cfm This lgtm. You can see the three expected commits here: https://github.com/weblate-fpf/securedrop-client/commit/939536334f6060db916b1d7c5c20cee1eb54a0f0 and when I run the client with the selected language as Spanish, I see the username translation. Are we ready to move this from `securedrop` to `securedrop-client` (https://github.com/freedomofpress/securedrop-client/compare/main...1266-continuous-l10n#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R158) and merge? Anything else you'd like to do before a merge here?

**Comment by cfm** [comment]
@creviera in https://github.com/freedomofpress/securedrop-client/pull/1282#pullrequestreview-760272865:

> @cfm This lgtm. You can see the three expected commits here: [weblate-fpf@9395363](https://github.com/weblate-fpf/securedrop-client/commit/939536334f6060db916b1d7c5c20cee1eb54a0f0) and when I run the client with the selected language as Spanish, I see the username translation.

As expected!  :tada:  Thanks for running through it from start to finish.

> Are we ready to move this from `securedrop` to `securedrop-client` ([main...1266-continuous-l10ndiff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R158](https://github.com/freedomofpress/securedrop-client/compare/main...1266-continuous-l10ndiff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R158)) and merge? Anything else you'd like to do before a merge here?

This is done in c86325ecd14109d37245a210cb65a0a4882e18e5.  I've also tacked on 9d09d240ae66c818eea1e1229174768bb4a0924e to fix a bug in my `jq` logic in the `supported-languages` target that I didn't catch while it was still pointing to `securedrop` rather than `securedrop-client`.

Otherwise, I think this is ready to go!  I can take care of the post-merge steps in Weblate once this is in `main`.

**Review by creviera — APPROVED** [review]
most recent changes lgtm - tests pass locally and in ci + talked more with cfm about why we had to switch to using gettext.[bind]textdomain (https://github.com/freedomofpress/securedrop-client/issues/1293)

**Pull request merged**
