### PR TITLE
chore: sync Weblate with monorepository structure

### LINKED ISSUE #1743: Weblate can't catch up automatically to the monorepository merge
Weblate is smartly declining to fast-forward the `securedrop/securedrop-client` component with 522 incoming commits from this repository.  I replicated this scenario on `weblate-sandbox` and found that:

1. Weblate's outgoing commits now have conflicts, because they still update files under `securedrop_client/locale`, which now lives at `client/securedrop_client/locale`.
2. We can update these paths, but then the *incoming* merge may conflict.  (It did on `weblate-sandbox`, anyway, because it had a different head to begin with; let's not risk it on `weblate`.)
3. We can reset Weblate from Git, but then we lose all the pending translations in Weblate's outgoing commits.

I've sketched the necessary intervention in #1742, which I'll pick up on Monday with a snapshot of `weblate`'s database and filesystem for safety's sake.

### PR DESCRIPTION
**Pull request by cfm**
To fix #1743:

1. [x] This branch begins with 201824f78b76940e0f1cba320e57128cfc2a94d0, which restores the `securedrop_client/locale` hierarchy from just before 9973f9e43b1b58dd4910f8b956639b0c6837e6b9, when it was moved to `client/securedrop_client/locale`.

Now:

2. [x] Change #1548's base branch to this branch and merge it in here.
3. [x] In Weblate, lock `securedrop/securedrop-client` translations.
4. [x] On this branch, move `securedrop_client/locale` back to `client/securedrop_client/locale`.
5. [ ] Merge this branch into `main`.
6. [ ] In Weblate, reset `securedrop/securedrop-client` from `main`, now including the changes merged from #1548.
7. [ ] In Weblate, add the `client/` prefix to the configuration of `securedrop/securedrop-client`.
8. [ ] In Weblate, unlock `securedrop/securedrop-client`.

### CODE REVIEW

**Comment by cfm** [comment]
This is ready for review.  The one mystery here is why the Bookworm `proxy_*` jobs are failing consistently in `proxy install`.  @legoktm, would you be willing to take a look tonight or tomorrow?

**Review by zenmonkeykstop — APPROVED** [review]
Moves LGTM, ok to proceed with remaining tasks after merge.

**Comment by zenmonkeykstop** [comment]
(iirc proxy bookworm failures are due to pyyaml dep not being available)

**Comment by cfm** [comment]
Thanks, @zenmonkeykstop.  I've completed the post-merge steps in Weblate:

> 6. [x] In Weblate, reset `securedrop/securedrop-client` from `main`, now including the changes merged from #1548.
> 7. [x] In Weblate, add the `client/` prefix to the configuration of `securedrop/securedrop-client`.
> 8. [x] In Weblate, unlock `securedrop/securedrop-client`.

—with the exception that once Weblate had no conflicts with `main`, step (6)'s reset was not necessary, and step (7) immediately picked up the translation files under `client/securedrop_client/locale/*`.

**Pull request merged**
